### ISSUE TITLE
Passing State to Action Creators

### ISSUE THREAD

**Issue by iammerrick** [rackt/react-redux#102]
In the case where you need to read state in an action creator what is the best way to do so... For example suppose I have an action creator that gets a new user object:

```javascript
export function load(state) {
  return (dispatch) => {
    if (getUser(state)) return null;

    get()
      .then((response) => {
        dispatch({
          type: AppConstants.USER_LOAD_SUCCESS,
          payload: {
            response
          }
        });
      });
  }
} 
```

Notice it is configured ahead of time with the current state, this enables the action creator to decide if it should really fire the action or not. Currently the mapping state and actions to components is separated, what do you do when an action creator needs access to state?

```javascript
export default connect((state, props) => {
  return {
    user: getUser(state)
  };
}, (dispatch) => {
  // I want state here to configure my action creator!
  return {
    load: () => dispatch(load(state))
  }
})(User);
```

**Comment by iammerrick** [comment]
How are others implementing fire and forget actions for incrementally loading data. Sprinkling the logic into every component and only firing conditionally?

**Comment by mikeyamadeo** [comment]
```js
export function load() {
  return (dispatch, getState) => {
    const state = getState()
    if (getUser(state)) return null;

    get()
      .then((response) => {
        dispatch({
          type: AppConstants.USER_LOAD_SUCCESS,
          payload: {
            response
          }
        });
      });
  }
} 
```

is not the second parameter provided when using redux-thunk the getState function?

**Comment by iammerrick** [comment]
@mikeyamadeo Bingo. Thanks!

**Comment by tomascharad** [comment]
What if you are using redux-saga, how would you access the state without using redux-thunk?

**Comment by markerikson** [comment]
@tomascharad : I believe Redux-Saga provides a `select()` operation, which you would use roughly like:

```js
const allTheState = yield select(state => state);
const oneSmallPieceOfState = yield select(someSpecificSelectorFunction);
```

**Comment by tomascharad** [comment]
Correct, forgot to update! thanks @markerikson.
