### ISSUE TITLE
Better way to fetch data from connected component?

### ISSUE THREAD

**Issue by chadly** [rackt/react-redux#103]
I have a component that, given a `User` will display user profile information. Here is a simplified version:

#### `user.js`
```js
import React, { Component, PropTypes as t } from "react";

export default class UserProfile extends Component {
	render() {
		const user = this.props.user;

		if (user.isLoading) {
			return <span>Loading...</span>;
		}

		return <span title={user.username}>{user.email}</span>;
	}
}

UserProfile.propTypes = {
	user: t.object.isRequired
};
```

We use this in places where we have the `User` object loaded and we want to show user information. However, there are a lot of places where we don't have the user object loaded (we just have a username or user ID) deep in the component tree and we also want to show user information. We usually solve this by also including a "containerized" version of this component which wraps the component and takes a `username` to fetch the `User` and pass it down to the original component.

However, now that we are using redux, I'm having trouble finding an elegant way to use a connected component to do this.

#### `user-container.js`
```js
import UserProfile from "./user";
import { fetchUser } from "./actions/user";
import { connect } from "react-redux";

const Container = connect((state, props) => {
	//I'd like to somehow dispatch the fetchUser action here before I query the store state
	const user = state.users[props.username];
	return { user };
})(UserProfile);

Container.propTypes = {
	username: t.string.isRequired
};

export default Container;
```

As soon as the `fetchUser` action is dispatched, the store state will reflect that the user is loading and not pass an `undefined` for the `user` prop.

In order to make this work with redux, we've settled on doing something like this:

#### `user-container.js`
```js
import React, { Component, PropTypes as t } from "react";
import UserProfile from "./user";
import { fetchUser } from "./actions/user";
import { connect } from "react-redux";

class FetchingComponent extends Component {
	componentDidMount() {
		this.props.fetchUser(this.props.username);
	}

	componentWillReceiveProps(nextProps) {
		if (nextProps.username !== this.props.username) {
			this.props.fetchUser(nextProps.username);
		}
	}

	render() {
		if (!this.props.user) {
			//have to deal with the case where the store state is
			//returned before the fetch action is dispatched
			return null;
		}

		return <MainComponent {...this.props} />;
	}
}

FetchingComponent.propTypes = {
	fetchUser: t.func.isRequired,
	username: t.string.isRequired,
	user: t.object,
};

const Container = connect((state, props) => {
	const user = state.users[props.username];
	return { user };
}, dispatch => {
	return {
		fetchUser: username => dispatch(fetchUser(username))
	};
})(FetchingComponent);

Container.propTypes = {
	username: t.string.isRequired
};

export default Container;
```

This works the way we want it to. It keeps the original `UserProfile` component clean and redux-unaware. It doesn't worry about fetching users or dealing with application state, it just displays profile information for whatever user it is given. It delegates the actual fetching of the user to the `FetchingComponent` and the connecting to the store state to the `Container` component (via redux's `connect`).

But, it feels like a lot of boilerplate for something that I feel like is very common (fetching data before you display it). I was wondering if anyone has any ideas on how to reduce the boilerplate and/or maybe there is something simple I am missing that will make this much easier?

**Comment by gaearon** [comment]
I think this is the same as https://github.com/rackt/react-redux/issues/47.
See https://github.com/rackt/react-redux/issues/47#issuecomment-139893624.

**Comment by KaroseLiu** [comment]
@gaearon Hi I have a question about the way to connect the component.

Here is the code:
`import Component from '../components/bp-hack'
import { connect } from 'react-redux'
import { dicoveryDevice, stopDiscoveryDevice, connectDevice } from '../actions/bp-hack'

const mapStateToProps = (state) => ({
  ...state.bpHack,
})

const temp = connect(
  mapStateToProps, { dicoveryDevice, stopDiscoveryDevice, connectDevice }
)(Component)

class container extends temp {
  componentWillMount() {
    super.componentDidMount && super.componentDidMount()
    this.store.dispatch(dicoveryDevice())
  }
  componentWillUnmount() {
    super.componentWillUnmount && super.componentWillUnmount()
    this.store.dispatch(stopDiscoveryDevice())
  }
}

export default container`

so this way, it will connect the component firstly then do the didMount, so what's the different between the 'before' and 'after' connect the component and the cons or pros.

Thanks,

**Comment by markerikson** [comment]
Don't use multiple levels of inheritance with React components.  It's a bad idea for a number of reasons.

Also, you should really ask that kind of question over on StackOverflow instead.  More people will see it, and you're more likely to get a good answer.
