### ISSUE TITLE
router with redux 

### ISSUE THREAD

**Issue by macsen110** [rackt/react-redux#110]
should i connect every smart component  that applying with route, i'm not clear about redux with react-router,   how i handle every component using redux

**Comment by gnoff** [comment]
Could you clarify the question?

**Comment by macsen110** [comment]
yeah, i have modify the issue! it just i am not clear about using redux in react-router!

**Comment by gnoff** [comment]
It certainly can make sense to connect your handler components for React Router routes. you can also perhaps connect a component or multiple components further down the route handler component tree, it's really up to you in terms of where the proper factoring is.

**Comment by gaearon** [comment]
Please see https://github.com/rackt/redux/tree/master/examples/real-world for a Redux example with React Router.
