### ISSUE TITLE
WrappedComponent.defaultProps is missing in mapStateToProps

### ISSUE THREAD

**Issue by wenbing** [rackt/react-redux#111]
```js
class Foo extends React.Component {
  render() {
    return <div>this.props.bar</div>
  }
}

Foo.defaultProps = {
  bar: 'baz'
}

module.exports = connect(function mapStateToProps(state, props) {
  console.log(props.bar) // undefined 
})(Foo)
```

**Comment by gaearon** [comment]
`connect()` returns a new component. If you'd like `defaultProps` to be present on it, you need to put `defaultProps` *on it*:

```js
class Foo extends React.Component {
  render() {
    return <div>this.props.bar</div>
  }
}

Foo = connect(function mapStateToProps(state, props) {
  console.log(props.bar) 
})(Foo)

Foo.defaultProps = {
  bar: 'baz'
}

module.exports = Foo;
```

**Comment by arcanis** [comment]
@gaearon shouldn't this be handled by the library? It doesn't feel very intuitive this way, and doing the opposite (`delete`-ing the `defaultProps` property from the wrapper element) could certainly help.

**Comment by markerikson** [comment]
No, the current behavior makes sense based on both the tooling, the language syntax, and the conceptual idea of defining "original" components vs defining wrappers for them.

**Comment by kusmierz** [comment]
But this doesn't work with new syntax `static defaultProps` inside the class...

**Comment by WalidKurchied** [comment]
@gaearon Dan is the solution you mentioned still applicable or do we have a better solution to achieve this ?
