### ISSUE TITLE
Changing mapStateToProps doesn't hot reload?

### ISSUE THREAD

**Issue by ronag** [rackt/react-redux#115]
Not sure if this is expected or not. But when updating `mapStateToProps` components don't seem to re-execute the mapStateToProps function.

**Comment by gaearon** [comment]
Yeah, with the tooling overhaul it's a bit of grey area right now. Let's keep it open.

**Comment by gaearon** [comment]
Let's track this in https://github.com/gaearon/babel-plugin-react-transform/issues/26 instead. You can also keep using React Hot Loader until it is fixed. With React Hot Loader, `mapStateToProps` should get reloaded just fine. When the issue in Babel plugin is fixed, it will work with React Transform too.

**Comment by gaearon** [comment]
You might be interested in https://github.com/reactjs/redux/pull/1455.

**Comment by gaearon** [comment]
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I encourage you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!

**Comment by glenjamin** [comment]
> This is fixed in React Hot Loader 3.
> It is built with lessons learned from both React Hot Loader and React Transform.
> It’s still in alpha but I encourage you to check it out!

@gaearon Great stuff! ran into this today when teaching redux to someone. I'll give it a whirl :)
