### ISSUE TITLE
Why only `mergeProps` called when component isn't pure?

### ISSUE THREAD

**Issue by vslinko** [rackt/react-redux#118]
First of all, I'm using Relay. It means that redux own only part of my state and I have a problem with it.

I wrapped my `App` component using `connect` because I want to get locale info from store.
If I keep `pure` option as `true` then `connect` prevents re-rendering, because nothing changed in redux.
But, If I set `pure` option into `false`, `connect` doesn't recall `mapStateToProps` and `mapDispatchToProps`, so `stateProps` and `dispatchProps` are cached forever.

Is it a bug?

https://github.com/rackt/react-redux/blob/master/src/components/createConnect.js#L93

**Comment by gaearon** [comment]
Might be. Can you submit a failing test?

**Comment by epeli** [comment]
Seems like a bug to me. I think `this.updateStateProps(nextProps)` should be called inside the `if (!pure) { ... }` statement.

I'll fix this in couple of days (if you don't beat me to it with a PR). Meanwhile can you try whether it fixes the issue for you?

**Comment by vslinko** [comment]
I think it also should include `this.updateDispatchProps(nextProps)`

**Comment by vslinko** [comment]
> Meanwhile can you try whether it fixes the issue for you?

I found a workaround, so I can't test it right now, but I sure it will work.

**Comment by epeli** [comment]
@vslinko I try whether #122 fixes this for you.

**Comment by vslinko** [comment]
@epeli it works, thank you
