### ISSUE TITLE
Could not find "store" error, the root is wrapped in a Provider

### ISSUE THREAD

**Issue by julienvincent** [rackt/react-redux#119]
I'm structuring my project almost exactly like the [real-world](https://github.com/rackt/redux/tree/master/examples/real-world) redux example, and have wrapped my react-router in a Provider with the store specified, but after trying to apply connect() to a component I get the error:

`Uncaught Error: Invariant Violation: Could not find "store" in either the context or props of "Connect(Home)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Home)".`

# render

```javascript
import { render, createFactory } from 'react'
import { Provider } from 'react-redux';
import router from './router/router'
import store from './flux/store'

window.onload = () => {
    render(createFactory(Provider)({store: store},
        () => router
    ), document.body)
};
```

# Router

```javascript
import { _ } from 'factories'
import { Router, IndexRoute, Route } from 'react-router'
import history from 'history/lib/createBrowserHistory'

import Home from '../components/home/home'

let route = _(Route),
    index = _(IndexRoute);

let router = _(Router)({history: history()},
    route({path: 'home', component: Home})
);
export default router;
```

# Component

```javascript
import React, { PropTypes } from 'react'
import { div } from 'factories'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux';
import * as users from '../../flux/actions/users'

class Home extends React.Component {

    constructor() {

        super();

        this.state = {}
    }

    render() {

        return (
            div({})
        )
    }
}

export default connect(
    state => {
        return {
            users: state.users
        }
    },
    dispatch => bindActionCreators(users, dispatch)
)(Home)
```

**Comment by gaearon** [comment]
Please see https://github.com/rackt/react-redux/issues/57. It's also on the "Troubleshooting" doc page: https://github.com/rackt/react-redux/blob/master/docs/troubleshooting.md#troubleshooting

**Comment by alex-wilmer** [comment]
I think it's worth leaving a link to the testing docs here http://redux.js.org/docs/recipes/WritingTests.html as its how I came across the solution for this issue: exporting the unconnected component.

**Comment by EugeneHlushko** [comment]
@alex-wilmer Thanks for leaving the link wide open in here, i would even go further here because this one is google top1 url for now and easy to reach:

**In your tests, import the connect()'ed component via curly braces like so to avoid the error:**
import { App } from './App'

While in your app you still use default imports:
import App from './App'

**Comment by szare** [comment]
@alex-wilmer thank you so much, this solved my problem too.

**Comment by Aadriya** [comment]
I HAve samme error


Invariant Violation: Could not find "store" in either the context or props of "Connect(App)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(App)".
   at invariant (/home/megha/public_html/universal-react-example/node_modules/invariant/invariant.js:42:15)

**Comment by Adzz** [comment]
...And further to that if you're using [ESlint](http://eslint.org/) and you are getting a [`no-named-as-default`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-as-default.md) error once you follow this pattern for testing, the TLDR is they can't co-exist, you'll have to disable that rule.

As suggested [here](https://github.com/benmosher/eslint-plugin-import/issues/468) and [here](https://github.com/benmosher/eslint-plugin-import/issues/544)

**Comment by YacheLee** [comment]
```
//Exporting your Header component instead of redux-wrapped component
export class Header extends Component{
	render(){return <div>HELLO WORLD</div>;}
}

function mapStateToProps(state){
	return state;
}

export default connect(mapStateToProps,{logout})(Header);

//Test your pure component
import {shallow} from "enzyme";
import {Header} from "../../src/containers/Header";
let wrapper = shallow(
<Header {...props} />
);
`console.log(wrapper.debug());
```

**Comment by dougbacelar** [comment]
if you dont wanna disable the eslint rule, you can change the name of the import:
``` javascript
import ConnectedComponent from './Component';
```

**Comment by dougbacelar** [comment]
If you dont want to disable the rule you can change the name of the import:

``` javascript
import ConnectedComponent from './Component';
```
