### ISSUE TITLE
Issue with react-router@1.0.0-rc1

### ISSUE THREAD

**Issue by pbreah** [rackt/react-redux#120]
I'm using react-redux@2.1.2 and react-router@1.0.0-rc1

I'm using this snippet to bootstrap redux with react-router:

```javascript
// on main.js
var rootRoute = {
    component: 'div',
    childRoutes: [{
        path: '/',
        component: require('./components/App'),
        childRoutes: [
            require('./routes/Route1'),
            require('./routes/Route2')
        ]
    }]
};
const store = configureStore();
React.render((
    <Provider store={store}>
        {() =>
            <RouterExtended routes={rootRoute} />
        }
    </Provider>
), document.getElementById('main-content'));

// on components/App.js
class App extends Component {
    render () {
        const { children } = this.props; // children is undefined
        return (
            <div className="col-md-12">
                <div className="row">
                    <div className="col-md-12">
                        {children}
                    </div>
                </div>
            </div>
        );
    }
}
```
This makes it show a blank page.

It was working fine on react-router beta3 but on this update it stopped working.

**Comment by gaearon** [comment]
If it broke after updating the router, why ask in `react-redux` repo? I'm closing as it doesn't appear related to React Redux.

**Comment by pbreah** [comment]
If I don't use react-redux, it works. You can check if needed the huge-apps example here: https://github.com/rackt/react-router/tree/v1.0.0-rc1/examples/huge-apps

I'm reporting it here because there seems to be an incompatibility between the Provider and the Router (on rc1) that are not playing well together.

If I go to the react-router repo to report this, they would say that the demo works for them (because they are not using react-redux)... eventually react-router will reach a stable 1.0 version and would break everyone's react-redux implementation as people update their dependencies if this incompatibility persists.

Sorry for the confusion,

Thank you

**Comment by gaearon** [comment]
I can assure you there is no inherent incompatibility between React Router and React Redux.
Provider and Router have no relation to each other and can't break each other.

Please put up a project reproducing the problem, and I can take a look what's breaking.

**Comment by pbreah** [comment]
@gaearon you were right.

It was the way the new version of react-router handled the history with:
```javascript
import createHistory from 'history/lib/createBrowserHistory';
```
instead of the beta3 way:

```javascript
import { history } from 'react-router/lib/History';
```

It was a bit tricky to troubleshoot. The react-router team is changing the API too much. Thanks for your re-assurance that it was not the cause of the issue, it helped anyways.

Also congrats for react-redux, awesome work.
