### ISSUE TITLE
How can I update a component having no parentChild relationship from another component

### ISSUE THREAD

**Issue by sap9433** [rackt/react-redux#121]
Le me simplify the question . Component x as a button , doesn't know about another component y . when I click on x , y should change it's color . How can I do this with redux

**Comment by gaearon** [comment]
Keep the color as part of the Redux store’s state.

Both components are connected with `connect()` from `react-redux`. When component X is clicked, you call `this.props.dispatch(changeColor(color))` where `changeColor` is your Redux action creator. The reducer will be called, and it should return the color from the action. Then component Y, which is also `connect()`-ed, receives the new color via props.

Please consult [Usage with React](http://rackt.github.io/redux/docs/basics/UsageWithReact.html) for a more in-depth intro.
