### ISSUE TITLE
"Batch updates"?

### ISSUE THREAD

**Issue by vojtatranta** [rackt/react-redux#124]
I encountered [this discussion](https://github.com/rackt/react-router/issues/2101#issuecomment-143744180) in react-router repo and it made me think.

If I navigate in app that uses redux to some other page. It is obvious that lots of keys in state will change somehow.
I don't care in my current apps, I just let my root components rerender many times (because store changes many times) and I rely on shouldComponentUpdate implementation to optimize things.
But I think that it is really waste calling render so many times. 
I think it would be nice if we could call some kind of batch update on state without calling changed() on store multiple times.
I would like to here some other opinions, thanks.

**Comment by gaearon** [comment]
Does https://github.com/tappleby/redux-batched-subscribe solve this problem for you?

**Comment by vojtatranta** [comment]
Maybe, docs are not the the best. But still would like to know you opinion.

**Comment by gaearon** [comment]
React plans to implement built-in batching for all `setState` calls later. For now, feel free to use a custom debouncing solution like https://github.com/tappleby/redux-batched-subscribe.

>It is obvious that lots of keys in state will change somehow.

If there's one action, there will be only one store change. If there are many actions, you can try avoiding firing many actions on route change.

**Comment by vojtatranta** [comment]
There is one action and in order to change the state all the reducers that should be changed by navigating react to this action (type: STATE_CHANGED), therefore there are lot of change events.

I think Relay may be right solution to this, but I haven't tested it yet.

Anyway, many thanks!

**Comment by gaearon** [comment]
>There is one action and in order to change the state all the reducers that should be changed by navigating react to this action (type: STATE_CHANGED), therefore there are lot of change events.

There is not a lot of state events. Redux does not have many stores. Every reducer is called on action, but **subscribers are only notified once after all reducers have handled the action**.

>I think Relay may be right solution to this, but I haven't tested it yet.

Relay is a framework focused on declarative queries, optimistic mutations, etc. However great it is, it has does not seem to have a relation to this question to me.

**Comment by vojtatranta** [comment]
Really? So I must have bug in my code, many thanks!

**Comment by Altiano** [comment]
Just wondering whether react already implement built-in batching or not? @gaearon

**Comment by markerikson** [comment]
@Altiano : this is the wrong place to ask that question.

That said, React implements batching for multiple `setState` calls in the same event handler sequence.
