### ISSUE TITLE
connect() not returning a valid React.Component

### ISSUE THREAD

**Issue by erikras** [rackt/react-redux#125]
It's my understanding that `connect()(MyComponent)` is going to return a HOC that wraps `MyComponent`. It _seems_ like I should be able to do this wrapping anywhere, even in a `render()` function, but something is breaking down. I have something like:
```js
render() {
  const ConnectedComponent = connect(mapStateToProps)(ComponentToWrap);
  return <ConnectedComponent {...this.props}/>;
}
```
But this generates an Invariant Violation: `A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object`.

The warning is coming from [`ReactCompositeComponent.js:170`](https://github.com/facebook/react/blob/v0.14.0-rc1/src/renderers/shared/reconciler/ReactCompositeComponent.js#L168-L174).

`Component.isReactClass` is `undefined`, and `inst` **_is_** an `instanceof` `Component`. I'm not sure how my instance, instantiated a few lines above, being an `instanceof` my component is at all surprising and worthy of an error, but that's what's happening.

What am I missing? Why is `connect()` not returning a valid React component?

**Comment by gaearon** [comment]
Any chance you have a duplicate React creeping in? For example you might have 0.13 and 0.14 side by side which could cause weird issues like this.

**Comment by gaearon** [comment]
I just tried adding a test like this to `connect.spec.js`:

```js
    it.only('should remove undefined props', () => {
      const store = createStore(() => ({}));

      class X extends Component {
        render() {
          class Lol extends Component { render() { return <div />; } }
          const Something = connect()(Lol);

          return (
            <Something />
          );
        }
      }

      TestUtils.renderIntoDocument(
        <ProviderMock store={store}>
          <X />
        </ProviderMock>
      );
    }
```

It passes.

**Comment by gaearon** [comment]
By the way, just in case, you should never do this:

```js
render() {
  const ConnectedComponent = connect(mapStateToProps)(ComponentToWrap);
  return <ConnectedComponent {...this.props}/>;
}
```

It means a new type is created on every `render`, so React kills the DOM and state on every render.

**Comment by erikras** [comment]
I was rapidly prototyping something, and it felt naughty. It should be okay if I save my `ConnectedComponent` class as `this.ConnectedComponent` and only generate it when the props that I'm using for the `connect()` call change, right?

**Comment by erikras** [comment]
React needed to be a peer dependency. Thanks! :+1:

**Comment by gaearon** [comment]
>I was rapidly prototyping something, and it felt naughty. It should be okay if I save my ConnectedComponent class as this.ConnectedComponent and only generate it when the props that I'm using for the connect() call change, right?

Hmm. I suppose so.
