### ISSUE TITLE
Get closer to Elm architecture

### ISSUE THREAD

**Issue by gaearon** [rackt/react-redux#136]
It seems that with the current `Provider`/`connect` and Smart/Dumb component distinction, some things from [Elm Architecture](https://github.com/evancz/elm-architecture-tutorial/) become harder than they should be. In particular, nesting actions, and examples like “generic list” (https://github.com/rackt/redux/issues/822).

It is possible that we need to tweak the API and conventions to better represent Elm Architecture and thus benefit from it. How exactly, I'm not sure yet.

**Comment by aflatter** [comment]
@gaearon Just out of interest: Was there any conclusion on this topic?

**Comment by gaearon** [comment]
I don't think it makes sense for us to do this. Neither Redux Middleware, nor React play well with Elm-like nesting. If somebody wishes to write their app in a completely Elm Arch-like way, they are free to do so: they just wouldn't use middleware, and would compose updater functions at the component level.

**Comment by gaearon** [comment]
Relevant new discussion: https://github.com/reactjs/redux/issues/1528
