### ISSUE TITLE
"Required module not found" with Flow

### ISSUE THREAD

**Issue by msolli** [rackt/react-redux#137]
I'm experimenting with Flow, but I'm getting errors when importing react-redux:
```
/Users/<...>/foo.js:4:33,45: react-redux
Required module not found
```

I've made the error go away by adding this to .flowconfig:
```
[options]
module.name_mapper='\(react-redux\)' -> '\1/lib/index'
```

This might by caused by facebook/flow#654. Maybe the error will go away when that issue is fixed. In the meantime, is there anything that could be done in react-redux to avoid the above work-around?

**Comment by gaearon** [comment]
I don't really know enough about Flow to fix this.
@leoasis, any ideas?

**Comment by leoasis** [comment]
Mmm since react-redux isn't even typed, perhaps a better option would be to just add it in the ignore paths?

If you feel adventurous you can even grab the declaration modules in [here](https://github.com/rackt/redux/pull/817) and try them so you can have the react-redux usage type checked (and `redux` and `redux-thunk` if you're using it). You'd need to put those files in a folder and specify them in the `[libs]` option in .flowconfig.

**Comment by msolli** [comment]
Thanks guys. I had stupidly ignored every package.json in my project in .flowconfig, which caused all sorts of strange problems. Sorry for the noise. I'll check out those declaration files.

**Comment by averyvery** [comment]
Ran into this issue myself with the flow config of ```[ignore]
.*/node_modules/.*

[options]
module.system.node.resolve_dirname=apps
```

Other modules seem to import correctly, but for some reason flow throws "not found" for `react-redux` in particular. Still looking into this...

**Comment by averyvery** [comment]
Ah, my fix was to just create an empty stub and map to it: 

```
export default {};
```

```
module.name_mapper='\(react-redux\)' -> '<PROJECT_ROOT>/flow/GeneralStub.js.flow'
```

**Comment by ericmasiello** [comment]
@averyvery can you give a bit more detail on your approach? where did you put these files?

**Comment by averyvery** [comment]
@ericmasiello sure:

```
// flow/GeneralStub.js.flow
export default {};

// .flowconfig
module.name_mapper='\(react-redux\)' -> '<PROJECT_ROOT>/flow/GeneralStub.js.flow'
module.name_mapper='\(immutable\)' -> '<PROJECT_ROOT>/flow/GeneralStub.js.flow'
```

**Comment by bevanhunt** [comment]
Also works: 
module.name_mapper='\(react-redux\)' -> 'empty/object'
module.name_mapper='\(immutable\)' -> 'empty/object'

**Comment by hipertracker** [comment]
What about https://github.com/flowtype/flow-typed ?

**Comment by thisiskylierose** [comment]
@bevanhunt best answer ---> worked for me! Thanks.
