### ISSUE TITLE
Expose ES6 source

### ISSUE THREAD

**Issue by rygine** [rackt/react-redux#139]
Looks like the source in the /lib folder has already been transpiled with Babel. Could you put the ES6 version of the source code in the repository? Reading through the transpiled code is not very fun. ;)

**Comment by epeli** [comment]
Thr source is in src dir

**Comment by gaearon** [comment]
The source is in the `src` folder, both in repo and on NPM.
Maybe you're looking at some old package version that didn't have it, but we ship it now.
