### ISSUE TITLE
Firing actions in componentWillMount() or componentDidMount() is broken?

### ISSUE THREAD

**Issue by rygine** [rackt/react-redux#140]
If I fire an action before the parent `connect()` component mounts, the state does not propagate as the `connect()` component has yet to subscribe to the dispatcher.

Should actions be fired in these lifecycle methods? If so, what's the best way to ensure that these actions and the resulting state are passed down?

**Comment by gaearon** [comment]
Which version of React Redux are you running?
Please provide a failing test case because [we do have test case for this](https://github.com/rackt/react-redux/blob/f9dfe461b730530c1a04061d6018540173efd5d1/test/components/connect.spec.js#L112-L134).

**Comment by rygine** [comment]
After much digging, I found the problem. It has to do with a bad state selector which caused `shouldComponentUpdate()` to return `false` in the connector. All is well.
