### ISSUE TITLE
Connected component prevents all context propagations

### ISSUE THREAD

**Issue by rpominov** [rackt/react-redux#144]
Because connected components have aggressive `shouldComponentUpdate`, and `shouldComponentUpdate` doesn't support context, connected components basically stop any other context variables changes to propagate to their children.

Is there a recommended solution to this problem? I found `pure` option (`connect(..., {pure: false})`), which helps, but is there a better way?

**Comment by epeli** [comment]
Related https://github.com/facebook/react/issues/2517

**Comment by rpominov** [comment]
One possible solution to this is to only check state in `shouldComponentUpdate`, if state didn't change always return `true`, and allow targets's component to decide if it should be updated.

This seems like a reasonable default behavior to me — check in shouldComponentUpdate only stuff we manage (this.state), and delegate any other checks to user's components.

**Comment by rpominov** [comment]
Sorry, I didn't look very carefully at the code. It doesn't uses state the way I thought. But the idea I had in mind still should be possible. I'll try to make a PR.

**Comment by gaearon** [comment]
The only better option that using `{ pure: false }` if you rely on context propagation is helping React fix it, or helping library maintainers work around this context issue.

Related:

* https://github.com/facebook/react/issues/2517
* https://github.com/facebook/react/pull/3973

**Comment by rpominov** [comment]
> or helping library maintainers work around this context issue.

Well this is what I'm trying to do :)

I've made a PR with a possible fix #149 It requires a bit more work, but I wanted to ask first if this idea makes sense.

**Comment by gaearon** [comment]
>Well this is what I'm trying to do :)

Oh, I meant libraries-relying-on-context-propagation, e.g. https://github.com/rackt/react-router/issues/470.

Longer term it's React's problem, but there are feasible workaround for specific libs today.
As you can see, for example, React Redux isn't affected because it doesn't read *values* from context.

**Comment by alexeychikk** [comment]
Checkout my simple workaround:
https://gist.github.com/alexeychikk/add4db3397df9feb2a0daf155376a5a8

**Comment by GongT** [comment]
Provider → ConnectedRouter → connect(MyPageStructure) → Router[s]

`MyPageStructure` will prevent `Router` to re-render
