### ISSUE TITLE
Passing multiple redux stores down the rendering tree through context

### ISSUE THREAD

**Issue by wwwsevolod** [rackt/react-redux#150]
Hello there!

It is good to have one atom of data, but sometimes not :)

For example: if you want to store localization data, it is better to store it isolated of anything else, but with ability to update it and wait for reactive update of texts in app (if user changed language). Or if you have big app with big big forms, that have completely separated state (Like i have on work).

I think its would be handy to have a way to pass multiple stores and access it. My "proposal" is API like this:

```jsx
    {/* contextName defaults to default field that passed in context */}
    <Provider store={Store1} contextName="someName">
         <Provider store={Store2}>
                <AppTree />
        </Provider>
    </Provider>
```

where `<AppTree />` can be wrapped in `connect` where developer passes `contextName` to handle not default store, or it can be wrapped in many `connect`s and have data from many stores at one time.

It would not broke anything, as i see, and make react-redux a little bit more flexible.

Anything bad about it? Is it worth to implement in react-redux? If yes I'll try to make PR

**Comment by gaearon** [comment]
We will not support this, as multiple stores is against Redux paradigm.
I'm not sure how multiple stores are better for the scenarios you proposed.

If you need this, you can implement your own `<MultiProvider>` or even pass `store` as a prop down directly to every component that needs it.

**Comment by marcuswhit** [comment]
@gaearon Sorry to dig up a closed issue - but is the recommended way of accessing the store from descendent components to just pass the store as a prop down through the tree?  I want to subscribe to some state updates, and intend to use [redux-rx](https://github.com/acdlite/redux-rx) to do so, but just not sure on the best way to access the store from descendent components.

**Comment by gaearon** [comment]
You can use context just like connect() uses it.

**Comment by markerikson** [comment]
I don't have benchmarks, but yes, ref arrays should be faster because they're just mapping the IDs to the plain JS objects already in the store, while model arrays do have to create model class instances. Not sure if the perf difference is actually meaningful at all, but there is *some* difference.
