### ISSUE TITLE
RFC: wrap dispatch into a function to intercept actions at component level

### ISSUE THREAD

**Issue by salmanm** [rackt/react-redux#161]
I am trying to wrap the `this.props.dispatch` function so that I can intercept all the actions that a component `dispatch`es and do *something* with them. I have created a mixin that adds some default lifecycle methods and does much more than I showed below for simplicity. 

```

const dispatch = this.props.dispatch;

this.props.dispatch = function (action) {
    if ( /* action met certain condition */ ) {
        // do something
    }

    dispatch(action);
}
```

But React is not happy about setting props within the component, so it gives me warning

```
Warning: Don't set .props.dispatch of the React component. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props
```

I want to know if it is fine and I can ignore the warning or I can do something with `react-redux`' and achieve the same result without having to override `dispatch`?

I know I can create a middleware to intercept actions, but I want to do it at component level.

**Comment by gaearon** [comment]
Don't modify props, React doesn't let you do this, and it will break in future versions.
Instead use `mapDispatchToProps` to wrap the `dispatch`:

```js
class MyComponent extends Component {
  render() { ... }
}

function mapStateToProps(state) {
  // ... 
}

function mapDispatchToProps(dispatch) {
  return {
    dispatch: (action) => {
      /* do your thing here */
      return dispatch(action);
    }
  }
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MyComponent);
```

**Comment by jony89** [comment]
This solution will only apply on the component dispatch function. if the component uses redux-thunk ( for async functions ) then the dispatch within this functions will not go through the interceptor, so any change/use of the actual payload is impossible.

You may do something like : 

function myDispatch(action) {
    /* do your thing here */
    if (typeof (action) === "function") {        
        return action(myDispatch);
    } else {
        return dispatch(action);
    }
}

but this will make redux-thunk redundant and will require to duplicate its code.

**Comment by pankajvishwani** [comment]
I got into this issue today and here's what I did using @jony89's suggestion:

function mapDispatchToProps(dispatch) {
	return {
		dispatch: action => {
			if(typeof action === "function"){
				return action(asyncAction => {
					/* do your thing here */
					dispatch(asyncAction);
				})
			}else{
				/* do your thing here */
				return dispatch(action);
			}
		}
	}
}
