### ISSUE TITLE
There is any best practices to schedule updating?

### ISSUE THREAD

**Issue by azazdeaz** [rackt/react-redux#164]
Hi, i'm pretty new at Redux, thanks for everyone working on it!

When i have a very frequent stream of actions (ex. dispatching actions on every mousemove event) the ```connect``` HoC will update my component for each of the actions which makes it choke. 
There is any best practice to schedule updates to the next requestAnimationFrame? The best thing that i can think of is wrapping the store i giving to the ```Provider``` in the way that is defers the subscibe callbacks until the next animation frame.

**Comment by gaearon** [comment]
Yeah, that's pretty much what https://github.com/tappleby/redux-batched-subscribe does.

**Comment by azazdeaz** [comment]
Oh, sorry i thought i was googling long enough before my question...
Thank you, it works great!
