### ISSUE TITLE
Provider and @connect hide the component interface?

### ISSUE THREAD

**Issue by jamiewinder** [rackt/react-redux#165]
My code base isn't entirely React-based, so there are points in which I want to use React components in a non-React context. In this situation I have a component that acts as an editor form; the form takes model data as an input, and the component has a 'getValue' method to get the model data back with the changes made on the form. 

To do this, I'm effectively using the method explained here:
https://facebook.github.io/react/tips/expose-component-functions.html

So...
```javascript
const editor = ReactDom.renderComponent(<Editor model={model} />, ...);
...
editor.getValue();
```
However my component also uses react-redux, so the above actually looks like:
```javascript
const editor = ReactDom.renderComponent(<Provider store={store}><Editor model={model} /></Provider>, ...);
...
editor.getValue(); // Error
```
Plus, my Editor component has the `@connect` decorator. This appears to have the side-effect of hiding my component API. Is this a bug, or is there a way around this?

**Comment by gaearon** [comment]
Component interface is props.
Imperative methods are an escape hatch and you should almost never use them.

The right way to implement this component is

```
<Editor model={model} onChange={handleChange} />
```

and have it pass the value to `onChange`.
This way you don't need a ref and don't need to call methods.

That said if you're 100% sure you want to do it that way (non-React way), you can add `{ withRef: true }` as the fourth parameter of `connect()` and then you'll have access to the instance as `editor.getWrappedInstance().getValue()`. But this is an anti-pattern.

**Comment by jamiewinder** [comment]
Thanks, it works although it looks like I have to add the store as a prop rather than use the `<Provider>` component (unless there is a `getWrappedInstance` equivalent there?).

This is definitely a workaround, though your 'right way' is, I think, different to what I'm trying to do - I need some external code to *pull* the value out of the editor rather than be notified of changes as they occur. Kind of like the difference between the 'value' property of an `<input>` versus capturing it on a 'change' event.

**Comment by gaearon** [comment]
Is “pulling” an expensive operation?

**Comment by jamiewinder** [comment]
Not really, but it has side effects. It basically validates the data entered, updates the UI to indicate any validation errors, and - if there any no errors - returns the value object (else null). Admittedly, it's a bit messy as this is a project where React is being introduced gradually. 

The reason it's a bit awkward is that the 'Save' button is external to the editor (I'm using a third party dialog component which isn't React). As such, the logic in the Save button click handler is basically 'try and grab the current value from the editor component, then save it'.

**Comment by gaearon** [comment]
Yeah, well, the workaround you're using is the best you can have in this case.
As you transition to more React-ish code, you'll need fewer workarounds.

**Comment by jamiewinder** [comment]
Yes, hopefully! Thanks for your help.
