### ISSUE TITLE
[Question] Am I using redux right?

### ISSUE THREAD

**Issue by nicolabortignon** [rackt/react-redux#167]
Hi everyone, this is just a question,
I'd love to double check if I'm doing things right. I'm coming from ages of different frameworks, and I def want to avoid bad practices in the early stage.

I'm using this boilerplate: https://github.com/erikras/react-redux-universal-hot-example
and I'm writing in ES7.

I created:
- 1 reducer:    earlyUser.js
- 1 container:   landingPage.js
- 1 component:  registrationForm.js

In the landingPage, I'm including the methods from reducer in this way:

import { saveEmail, savePreferences, checkEmailExists } from 'redux/modules/earlyUser';

and I declare some handles
```javascript
 handleSubmitEmail(data) {
    this.props.saveEmail(data);
 }

 handleSubmitPreferences(data) {
    //some data manipulation
    this.props.savePreferences(data);
 }
```

and in the JSX part I just pass to my component the handlers:
```javascript
<registrationForm submitEmail= {::this.handleSubmit}   etc... >
```

Now inside the component, I linked the form submission to this handler:
```javascript
submitEmail() {
    if (this.validateEmail(this.state.email)) {
      this.props.submitEmailHandler(this.state);
    }
  }

```

Now my question is, where should I attach the .then  and .catch of the promise returned ?
Ideally I'd like to do inside the component.js  something like 
```javascript
this.props.submitEmailHandler(this.state).then( function emailRegisterCallback(){
   // move to next step
}).catch( function errorHandler(error){
  // there was an error
}
```
Is that correct?

**Comment by gaearon** [comment]
This is a usage question. Please ask it on StackOverflow, you're much more likely to get a quality answer there.

**Comment by nicolabortignon** [comment]
Done, for future references:

http://stackoverflow.com/questions/33323462/am-i-using-redux-correctly
