### ISSUE TITLE
"'location' of null" error in real-world example 

### ISSUE THREAD

**Issue by gregberns** [rackt/react-redux#171]
I'm totally new to redux... but it looks sick.

Seems to be an issue in the "DevTools". When I install and run "real-world" example, search for 'rackt', then click anything in DevTools, errors start appearing in the console:

Uncaught TypeError: Cannot read property 'location' of nullmapStateToProps @ App.js?7e8f:68

Version 3.0.4

To reproduce:
1) cd redux/examples/examples/real-world
2) npm install
3) npm start
4) Go to site in browser: http://localhost:3000/
5) Enter: 'rackt'
6) In the DevTools(redux's), click "Reset"

Error occurs....

**Comment by gaearon** [comment]
Thanks for the report. I'd say you should file this with `redux-router`.

By default it sets `router` state field to `null`, but I think it should have initial value before first change action. The app should never see `null` state there, I think, but `RESET` effectively gets us back to the initial state. The same error will occur if you “toggle” action in DevTools.

@acdlite Ideas?
