### ISSUE TITLE
Getting problems with mapDispatchToProps

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/react-redux#174]
Hello,

Im currently trying to `connect` a component with `react-redux`, but I'm having a bit of trouble and I'm not sure where I may be going wrong. (I'm using an alternative way to declare components without using classes https://gist.github.com/jquense/47bbd2613e0b03d7e51c) Heres the Component I'm trying to connect:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import SideMenu from './SideMenu.js';
import LeadsFilterBar from './LeadsFilterBar.js';
import Leads from './Leads.js';
import {connect} from 'react-redux';
import { bindActionCreators } from 'redux';
import * as LeadActions from './../../actions/actionCreators.js';


function LeadsList (props, reactElementInstance) {
    var instance = Object.create(React.Component.prototype);
        instance.context = reactElementInstance;
        instance.props = props;
        instance.render = function () {
            return (
                <div className="leadsList">
                    <div className="container-fluid">
                        <div className="row">
                            <div className="col-sm-12">
                                <div className="col-sm-2">
                                    <SideMenu/>
                                </div>
                                <div className="col-sm-10">
                                    <LeadsFilterBar onSearch={actions.searchLeads}/>
                                    <Leads loadLeads={actions.fetchLeads} userLeads={userLeads}/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            );
        };

    return instance;
}

function mapStateToProps(state) {
    return {
        userLeads: state.getIn(['leads']),
        savedLeads: state.getIn(['savedLeads']),
        searchedLeads: state.getIn(['searchedLeads'])
    };
}

function mapDispatchToProps(dispatch) {
    return {
        actions: bindActionCreators(LeadActions, dispatch)
    };
}

export var LeadsListContainer = connect(mapStateToProps, mapDispatchToProps)(LeadsList);
```

Just in case you're wondering I have wrapped the `Provider` around the root component and passed it the store. I get the following error from this code:

<img width="1280" alt="screen shot 2015-11-04 at 10 00 56 pm" src="https://cloud.githubusercontent.com/assets/8888991/10958760/981ab304-833f-11e5-8837-edc2e61b9c25.png">

The odd thing is webpack itself is not reporting an error for `actions` not being defined.

**Comment by gaearon** [comment]
Use a linter like ESLint, it would catch the error for you.
The error message is correct: you're using `actions` in your code which is never defined.
You can search for “actions” in the code and you will find it. :wink:

<img width="724" alt="screen shot 2015-11-05 at 22 00 07" src="https://cloud.githubusercontent.com/assets/810438/10978535/9a9a2fd2-8408-11e5-8806-76814a0a7e89.png">

**You probably meant to write `props.actions` there instead. Same for `userLeads`: you probably meant `props.userLeads`.**

However, there is no need to follow this pattern now that React 0.14 shipped.
Just write a functional component:

```js
function LeadsList (props, reactElementInstance) {
    return (
        <div className="leadsList">
            <div className="container-fluid">
                <div className="row">
                    <div className="col-sm-12">
                        <div className="col-sm-2">
                            <SideMenu/>
                        </div>
                        <div className="col-sm-10">
                            <LeadsFilterBar onSearch={props.actions.searchLeads}/>
                            <Leads loadLeads={props.actions.fetchLeads} userLeads={props.userLeads}/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
```

In React 0.14 you can write components this way.

**Comment by kennetpostigo** [comment]
@gaearon do you have a link to the functional component in React 0.14?

**Comment by gaearon** [comment]
It's described in release notes: https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by kennetpostigo** [comment]
Thank you, @gaearon !
