### ISSUE TITLE
Component not re-rendering when mapStateToProps receives empty array

### ISSUE THREAD

**Issue by lomteslie** [rackt/react-redux#176]
Hey there. I've read through all the troubleshooting steps and haven't been able to solve this. Hoping for some insight here...

I have a bunch of components connected in my app, with react-redux working beautifully. However, there are a couple of components that receive an array of objects as a prop, but they do not trigger a state change when they receive an empty array. Only when the array is populated. Is this expected behavior?

This is one of the mapStateToProps examples (using ImmutableJS):
```
export default connect(state => ({
  specialties: state.specialties.get('options'),
  selectedSpecialties: state.specialties.get('selected'),
  searching: state.specialties.get('searching')
}))(ChooseSpecialty);
```
If I log `state.specialties.get('selected')` in there I can tell I'm getting something, but when it's an empty array my component does not re-render, which I need it to do. Any thoughts?

**Comment by gaearon** [comment]
No, this is not the expected behavior.
We need more information.
Can you show the code of the related reducers?

**Comment by lomteslie** [comment]
Sure thing...
```
export function specialties (state = Map({}), action) {
  const searching = action.type === SETUP.SEARCH_SPECIALTIES;
  const updating  = action.type === SETUP.UPDATE_SELECTED_SPECIALTIES;
  const resetting = action.type === SETUP.RESET_STATE;

  if (searching) {
    switch (action.status) {
      case STATUS.START:
        return state.set('searching', true);
      case STATUS.SUCCESS:
        return state
          .set('searching', false)
          .set('options', action.payload.specialties);
      case STATUS.FAILURE:
        return state
          .set('searching', false)
          .set('error', action.payload.error);
      default:
        return state;
    }
  } else if (updating) {
    return state.set('selected', action.payload.specialties);
  } else if (resetting) {
    return state
      .set('searching', false)
      .set('selected', [])
      .set('options', []);
  }

  return state;
}
```

**Comment by gaearon** [comment]
What is `action.payload.specialties`?
Any change this is something that can get mutated from outside the reducer at a later point?

Please provide a reproducible example to help me understand the issue.

**Comment by gaearon** [comment]
I'll close for now because I don't currently believe this is an issue in React Redux.
If you find a way to reproduce (or make a failing test), I'll be happy to reopen.

**Comment by lomteslie** [comment]
Okay, your comment helped us figure it out. It turns out we did have a component (that maintains it's own state) that mutated the arrays along the way. Thanks for the help.

**Comment by gaearon** [comment]
:+1: Glad it works now, cheers.
