### ISSUE TITLE
Is it OK to return an ES6 class instance in mapStateToProps?

### ISSUE THREAD

**Issue by jjzazuet** [rackt/react-redux#177]
Like the title says. I wrote an ES6 class that I wanted to use to store state in my application.

However, upon setting it in my redux reducer, and returning it inside my connected component, I get this error message:

    Uncaught Error: Invariant Violation: `mapStateToProps` must return an object. Instead received [object Object].

Am I doing something wrong? Is this supported? Thanks for your time!

**Comment by gaearon** [comment]
No, you need to return a plain object because *its keys will be used as props*.
If you want to use a custom class for props, you need to pass it *as a specific prop*:

```js
function mapStateToProps(state) {
  // return new MyClass(state.something); <-- wrong
  return {
    lol: new MyClass(state.something) // will be available as this.props.lol in component
  };
}

**Comment by jjzazuet** [comment]
Ah OK, cool. Thanks!
