### ISSUE TITLE
Remove invariant requirement.

### ISSUE THREAD

**Issue by dzearing** [rackt/react-redux#178]
Seems like in your other projects, you've removed the invariant dependency. It would be nice to do it here as well if you get the chance. We're using systemjs builder to include react-redux, so it ends up needing to map the invariant dependency, and causes some issues when process is not defined. We can work around these, but it'd be nice to just minimize the dependency graph as much as possible.

I could make a PR if you want, but it's pretty simple, and it's up to you if you have a good reason to still have it.

**Comment by gaearon** [comment]
Even if we remove the `invariant` dependency we're still going to use `process.env.NODE_ENV` check to tell production from development builds. That's what React does too. When you use CommonJS build from NPM, you're supposed to shim it (e.g. via build tools like `envify` or webpack's `DefinePlugin`).

If you absolutely don't want to shim `process.env.NODE_ENV` yourself, please feel free to use the envified UMD builds in `react-redux/dist` (which is available in the NPM package).
