### ISSUE TITLE
Add support for React 0.14.2

### ISSUE THREAD

**Issue by haizz** [rackt/react-redux#188]
The latest version of React is 0.14.2, but react-redux depends strictly on 0.14.0.

**Comment by gaearon** [comment]
I don't think this is correct.
It depends on `^0.14.0` which is a [caret range](https://github.com/npm/node-semver#caret-ranges-123-025-004) and includes any 0.14.x release.

* [More info about semver](https://github.com/npm/node-semver)
* [Semver calculator](http://semver.npmjs.com/)
