### ISSUE TITLE
.babelrc causing babel transpile issues

### ISSUE THREAD

**Issue by tylerwgoza** [rackt/react-redux#190]
Babel (according to it's website as of November 13, 2015) does not have an option for `stage` or `loose` and these cause babel to blow up on transpile. Wondering if this serves some other purpose? I have opened the same issue on rackt/redux#1032

**Comment by gaearon** [comment]
Thanks, but there is no need to create multiple issues.
This is a hassle for maintainers.

The Babel configuration changed in 6.x.
We'll catch up eventually.
See https://github.com/rackt/redux/issues/1032#issuecomment-156489518.
