### ISSUE TITLE
Consider passing props down in Provider?

### ISSUE THREAD

**Issue by AlastairTaft** [rackt/react-redux#192]
I'm using react-router with redux. Not sure if this is best resolved in react-router, react-redux or there's a better solution.

In my route route App.jsx component I use cloneElement to pass some props down to immediate children. Not a big fan of this for now, but this is how my code has turned out.
```
  render() {
    let children = React.Children.map(this.props.children, function (child) {
      return React.cloneElement(child, {
        showSignup: self.showSignup,
        showLogin: self.showLogin,
      })
    }.bind(this))
    return <div className="App">
      {children}
    </div>
  }
```

Then my child route component LandingPage.jsx uses those props. This all works find until I use react-router's `createElement` method on the router. What this does is wrap all the route components in another component. 

```
  function createElement(Component, props) {
    return <Provider store={store}> 
      <Component {...props} />
    </Provider>
  }

  render((
    <Router history={createBrowserHistory()} createElement={createElement}>
      {routes}
    </Router>
  ), appContainer)
``` 

Now passing the props in in that createElement function is kinda useless because the props don't contain my `showSignup` and `showLogin` methods, they only contain the RoutingContext props of react-router. So my code breaks. To solve it I've had to extend react-redux's Provider class and pass down any extra props.

```
  class ProviderWithProps extends Provider {
    render () {
      var {children, store, ...otherProps} = this.props
      return React.cloneElement(React.Children.only(children), {...otherProps})
    }
  }

  function createElement(Component, props) {
    return <ProviderWithProps store={store}> 
      <Component {...props} />
    </ProviderWithProps>
  }

  render((
    <Router history={createBrowserHistory()} createElement={createElement}>
      {routes}
    </Router>
  ), appContainer)
```

Would updating the Provider class to include passing down extra props make any sense?

**Comment by AlastairTaft** [comment]
I have the same issue server side but I don't have a solution.

**Comment by gaearon** [comment]
Wrap `<Router>` itself into a `<Provider>`. Then you'll receive the element you wanted as a child and be able to add props to it.

```js
  render((
    <Provider store={store}>
      <Router history={createBrowserHistory()}>
        {routes}
      </Router>
    </Provider>
  ), appContainer)
```

**Comment by AlastairTaft** [comment]
Cheers
