### ISSUE TITLE
Getting the value of dispatch before rendering Provider

### ISSUE THREAD

**Issue by Zacqary** [rackt/react-redux#198]
I'm trying to avoid writing any container components (is that the new name for smart components?) at all. We're slowly implementing Redux in our codebase, so the top-level component is a moving target; it helps to keep all the React code completely unaware that it's being passed a `dispatch` at all so that we can easily nest a former top-level component inside a new top-level component.

My solution is:
```
function renderReduxProvider(store){
    var actions = props => Redux.bindActionCreators(objectContainingAllMyActionCreators, props.dispatch);
    var ConnectedComponent = ReactRedux.connect(myReducers)(MyComponent);
    return (
        <Provider store={store}>
            <ConnectedComponent actions={actions}/>
        </Provider>
    )
}
```

This works, except inside `MyComponent`, I have to say:
```
var actions = props.actions(props);
```

So the component's not aware that it's being passed `dispatch`, but it is aware that it's being passed a function instead of an object. It's not ideal.

What I'd really like to do is be able to access the `dispatch` value within my `renderReduxProvider` function, so that I can pass it into `bindActionCreators` immediately before passing it into a single React component.

Is that possible?

**Comment by gnoff** [comment]
`store` has `dispatch` as a property so just reference `store.dispatch` from within `renderReduxProvider`

**Comment by Zacqary** [comment]
I just found https://github.com/rackt/react-redux/blob/master/docs/api.md#inject-todos-and-all-action-creators-addtodo-completetodo--as-actions in the API docs a few minutes ago.

This is what I get for only reading the Quick Start.

Sorry about that!

**Comment by gnoff** [comment]
No problem
