### ISSUE TITLE
RN 0.15.0 is out

### ISSUE THREAD

**Issue by kinhunt** [rackt/react-redux#202]
and it uses react 0.14, how do we use react-redux with it?

**Comment by gaearon** [comment]
You can't. It uses React 0.14 *internally* but https://github.com/facebook/react-native/issues/2985 is still not fixed. Please keep tracking https://github.com/facebook/react-native/issues/2985.

**Comment by prashanth1509** [comment]
But still you can (hack) use _reactInternals._context instead of context.
