### ISSUE TITLE
Upgrading to react-native 0.15.0

### ISSUE THREAD

**Issue by nodkrot** [rackt/react-redux#203]
After upgrading to react native 0.15.0 and using react-redux 4.0.0
`import { Provider } from 'react-redux';`
produces following errors in the chrome debugger:
<img width="611" alt="screen shot 2015-11-25 at 7 29 56 pm" src="https://cloud.githubusercontent.com/assets/5076567/11412456/3abd07b2-93ab-11e5-9bc8-c407d5489090.png">

**Comment by ellbee** [comment]
I'm afraid they are not compatible at the moment. This notice from the readme explains the situation:

https://github.com/rackt/react-redux#react-native
