### ISSUE TITLE
[REQ] Babel update

### ISSUE THREAD

**Issue by NullDivision** [rackt/react-redux#206]
Would it be possible to update Babel to version 6? Version 5 interferes with newly created projects.

**Comment by duro** [comment]
I'm running into this as well in a react-native 0.16 project which uses Babel 6 under the hood. Looks like the .babelrc in react-redux throws an `unknown option` error.

**Comment by ajwhite** [comment]
I'm unable to build with the changes made to `stage` in 6, I believe

```
{
  "message": "TransformError: /Users/ajwhite/Development/OneMightyRoar/Robin/robin-rooms-react-0.16/node_modules/react-redux/native.js: [BABEL] /Users/ajwhite/Development/OneMightyRoar/Robin/robin-rooms-react-0.16/node_modules/react-redux/native.js: Unknown option: /Users/ajwhite/Development/OneMightyRoar/Robin/robin-rooms-react-0.16/node_modules/react-redux/.babelrc.stage",
  "type": "TransformError",
  "errors": [{}]
}
```

**Comment by NullDivision** [comment]
As a workaround for the `unknown option` issue was to install babel-core with the presets in my project and babel-cli globally. As long as there's no babel executable in the `./node_modules/.bin/` directory it installs its own.

**Comment by ajwhite** [comment]
Interesting, @NullDivision -- so you basically kill the local installations and rely on the global? In theory, it sounds like this might also let you compile with a different version of Babel? I'm currently using the `@connect` decorators that are no longer supported in Babel 6 (and also not resolved with the current workaround in [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy))

**Comment by NullDivision** [comment]
I'm not sure about the `@connect` decorators but all my dependencies work just fine with the global installation of babel-cli. For reference I'm using Webpack as my main builder and everything works as it should.

I need `babel-core/register` for runtime transpiling on Karma and Gulp but everything else uses the global binary.

**Comment by eadz** [comment]
I believe this is also causing an error with the react-native compatible branch, as the latest RN is using version 6 of babel.

**Comment by eadz** [comment]
Just an idea for another workaround - would using a precompiled version of react-redux would work? I see there is a precompiled version on the CDN, but this is not for the native version.

**Comment by NullDivision** [comment]
It's always a posibility but then what's the use of NPM and versioning? It also won't allow you to import it using ES6 unless you download the js file.

**Comment by martincik** [comment]
I've created PR with first attempt to integrate new Babel 6 with react-redux. It's running the `npm install` but I'm not able to run 'npm run test'. Anyone can help me? Thank you.

**Comment by NullDivision** [comment]
Not without a terminal dump.

**Comment by martincik** [comment]
I've been able to make it run, but there's one test that's failing: https://travis-ci.org/rackt/react-redux/builds/95561875

Help with this one case appreciated.

**Comment by gpbl** [comment]
I'm waiting for the PR to get merged so I can upgrade to 0.16 – I wonder is the PR intended for react-redux@3.1 right? AFAIK we can't use react-redux@4 with the current react-native version

**Comment by boldkhuu** [comment]
When will this PR be merged?

**Comment by gaearon** [comment]
Hey folks!

I'm a bit confused why everyone is waiting for us updating to Babel 6. The library is compiled to ES5 :-). You shouldn't care what it uses internally.

The real fix was to stop shipping `.babelrc`. We fixed that in 3.1.2 and 4.0.1.

**Comment by martincik** [comment]
The reason is that it breaks react-native apps builds. Can we also remove .babelrc from redux itself? It's also breaking for me on babel dependency.

Here's where it's failing for react-native apps (0.16):
```
uncaught error Error: ReferenceError: [BABEL] /Users/PROJECT/node_modules/redux/lib/index.js: Unknown option: /Users/PROJECT/node_modules/redux/.babelrc.stage
```

**Comment by NullDivision** [comment]
I don't know if it would work but could someone try moving the babelrc content into the package.json under "babel"? I think that might solve the issue.

**Comment by gaearon** [comment]
>The reason is that it breaks react-native apps builds.

The Babel version we use internally doesn't matter. What mattered is that we shouldn't have shipped `.babelrc` in the package at all. We fixed this already. 

And it is also already removed from Redux. Please update to the latest version.


@NullDivision As far as I know there is no issue to solve. What do you mean? It's already solved in the latest update to both packages.

**Comment by NullDivision** [comment]
I still see `.babelrc` on master.

**Comment by gaearon** [comment]
We don't need to remove it from the source. (We still need Babel right :-). We removed it from NPM distribution by using "files" whitelist in package.json.
