### ISSUE TITLE
Cannot require react-redux/native in the 3.x branch

### ISSUE THREAD

**Issue by janicduplessis** [rackt/react-redux#216]
975a9030a880a2e59f7843ed54134ee840f87ce9 broke the import, it should still ship with native.js to keep the same imports as before.

Thanks!

**Comment by gaearon** [comment]
Oh snap, you're right.

**Comment by gaearon** [comment]
Should be fixed in 3.1.2. Can you verify?

**Comment by janicduplessis** [comment]
Yes it's working now, thanks!
