### ISSUE TITLE
Hot reloading selector used in connect() does not work

### ISSUE THREAD

**Issue by rybon** [rackt/react-redux#220]
For example, when using `export default connect(mainMenuSelector)(MainMenu)` and changing the returned object in `mainMenuSelector`, these changes do not propagate to the React component after hot reloading.

However, when using `export default connect(appState => appState)(MainMenu)` and calling the `mainMenuSelector` from within `render()` with `this.props.appState`, it does work after hot reloading. What explains the difference here? I'm using the new way of hot reloading with https://github.com/gaearon/react-transform-boilerplate

**Comment by gaearon** [comment]
Please see https://github.com/rackt/react-redux/issues/115.

**Comment by gaearon** [comment]
This is fixed in [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).
It is built with lessons learned from both React Hot Loader and React Transform.
It’s still in alpha but I encourage you to [check it out](https://github.com/gaearon/react-hot-boilerplate/pull/61)!

**Comment by rybon** [comment]
Awesome, I will check it out! Thanks for all your hard work, I really appreciate it.
