### ISSUE TITLE
Connect could be decoupled from Redux

### ISSUE THREAD

**Issue by slorber** [rackt/react-redux#228]
Hi,

This is a follow-up of my [feedback](https://github.com/rackt/redux/issues/1176#issuecomment-167087348) about running a prod app with an internal framework that looks a bit like Redux, but is not Redux.

We'd like to migrate to Redux at some point for state management, and do so progressively. A thing that would be easy to do is start using connect/reselect with our own framework. Our framework has its own global atom, from which we can subscribe/unsubscribe and extract state object like a Redux store.

What I see of `connect` is that the logic and optimizations can probably be reused outside of the Redux world for any framework that shares the same low-level functionalities of the Redux store (like our internal framework or Baobab or many others)

I would be happy to make a PR for this if you are ok with the idea or move a generic connect to a separate NPM project on which React-redux will depend.

About hot reloading, I'm not sure how it works currently, is it coupled to Redux and may I have troubles with it?

**Comment by slorber** [comment]
Also don't want to open another issue for that but couldn't Redux devtools be plugged to an ELM app for example?

**Comment by gaearon** [comment]
In general this is probably doable but I'm wondering what kind of API you have in mind. We don't want to get lost in too much indirection. It might be easier to just fork the project and tweak it, as implementations are likely to diverge later anyway.

>Also don't want to open another issue for that but couldn't Redux devtools be plugged to an ELM app for example?

I don't think so. Elm communicates with JS via an abstraction but DevTools want to wrap your update logic. Elm has its own debugger anyway, right?

**Comment by DenisIzmaylov** [comment]
Looks very nice.

**Comment by slorber** [comment]
@gaearon I share your point that it's fine to copy/paste and fork and really like these posts on the subject:
- http://us3.campaign-archive2.com/?u=1090565ccff48ac602d0a84b4&id=92902a19e4&e=6dbbf45b40
- http://udidahan.com/2009/06/07/the-fallacy-of-reuse/

Here it seems that the API surface to implement the connect feature is very small and that an abstraction make sense (like you probably did for react-hot-api?). Also if it's possible to avoid forking and benefit from further optimizations done by the community without having to backport it's better for me :)

I would be interested to know how you see implementations could diverge because I'm not sure how it could happen unless new redux store methods are added?


-------------------------

Anyway I've found another simpler option.

```
export default PropTypes.shape({
  subscribe: PropTypes.func.isRequired,
  dispatch: PropTypes.func.isRequired,
  getState: PropTypes.func.isRequired
})
```

Let's consider the Redux store API as a reference implementation of a "react connect standart": I'll wrap my framework so that it exposes the exact same API in react context and it should work. Other frameworks could easily do the same too

**Comment by gaearon** [comment]
Yeah, as long as you expose that API you'll work with React Redux fine. You can even write `toReduxStore(customStore)` and the use Provider with it as well. 

I'll close then.
