### ISSUE TITLE
Component can't receive async props  in android and ios8

### ISSUE THREAD

**Issue by leaven** [rackt/react-redux#229]
I've been troubled by this problem for a few hours, I need some help.
Async action
		
	export function getLineList() {
    
    let line_id = splitLineId();

    return dispatch => {
        fetch('/api/passenger/line/detail?line_id=' + line_id)
            .then(response => response.json())
            .then(json => {
            dispatch({
                type: types.GET_LINE_LIST,
                data: json
            })})
    };
   }
Reducer
	
	export default function getLineList(state={}, action) {
	
		switch(action.type) {
			case types.GET_LINE_LIST:
				return Object.assign({}, state, action.data);
			default:
				return state;
		}
	}

Main Component

	
	function mapStateToProps(state) {
		console.log(state);
		return {
			data: state
		}
	}
	
	
	function mapDispatchToProps(dispatch) {
		return {
			actions: bindActionCreators(Actions, dispatch)
		}
	}
	
	let App = connect(
	    mapStateToProps,
	    mapDispatchToProps
	)(Main);
In ios9+, the result can be logged in `mapDispatchToProps`  when the result been dispatched in `getLineList` action while android and ios8 can't.
The react-redux version is `v4.0.0`, what's wrong.

**Comment by leaven** [comment]
The problem has been solved, sorry troubled.It turned out that *Object.assgin* wasn't supportted in those os.And babel 5+ did not translate it into ES5.

**Comment by gaearon** [comment]
Babel only translates syntax. You need to explicitly import `babel-core/polyfill` if you also want the polyfill (it's fairly large).
