### ISSUE TITLE
React Native problem: Cannot inject event plugin ordering more than once.

### ISSUE THREAD

**Issue by mcz** [rackt/react-redux#230]
This works perfectly with react-redux 3.x, but with 4.x it got broken.

It works with 3.x:

* Clone this repo: https://github.com/alinz/example-react-native-redux
* Run it in XCode, and it works perfectly.

With react-redux 4.x, it's broken:

* Delete all dependencies in package.json file so next time on npm install the latest will be installed
* Install the latest dependencies

```
cd example-react-native-redux/Counter
npm install react react-native react-redux redux redux-thunk --save
```

* In app/containers/app.js and counterApp.js remove the native suffix after react-redux import
* Open XCode project and Run it

```
open ios/Counter.xcodeproj
```

* You will get an error an Invariant Violation error: [please see this screenshot](https://www.dropbox.com/s/vqdrx5ghpmxkf4t/Screenshot%202015-12-28%2000.03.32.png?dl=0)

The problem is definitely with react-redux because if I comment the react-redux import lines and remove all code that depends on either connect or Provider, than it works perfectly.

Thank you,
Peter

**Comment by gaearon** [comment]
[From the README](https://github.com/rackt/react-redux#react-native):

>Until [React Native works on top of React instead of shipping a fork of React](https://github.com/facebook/react-native/issues/2985), you’ll need to keep using [React Redux 3.x branch and documentation](https://github.com/rackt/react-redux/tree/v3.1.0).
