### ISSUE TITLE
componentWillMount actions

### ISSUE THREAD

**Issue by chrishowes** [rackt/react-redux#234]
Is componentWillMount still the best spot for "on load" actions? Or is there any downside to firing them in the mapDispatchToProps before returning the map and keeping every component a function?

**Comment by gaearon** [comment]
`mapDispatchToProps` is presumed to be pure. Please don't do data fetching there. It may be called multiple times, etc. Yes, `componentWillMount` is the best way. You can also create a custom higher-order component that would wrap yours, so you can keep yours a function and wrap it.

**Comment by lauterry** [comment]
Hi @gaearon 

I'm not sure to understand your answer to @chrishowes .

Can you provide an example of what you mean by creating a custom higher-order component and how to use it.

Thx

Best regards

**Comment by gaearon** [comment]
https://github.com/markdalgleish/redial is a good example of what I mean.

**Comment by lauterry** [comment]
Thx. I'll have a look
