### ISSUE TITLE
Passing store inside iframe

### ISSUE THREAD

**Issue by lucadegasperi** [rackt/react-redux#240]
Hello, what I'm trying to do is render a part of an application inside and iframe element. The problem I'm facing is that there's no concept of store inside the iframe. 
```Could not find "store" in either the context or props of "Connect(Header)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Header)".```

How do I pass the store to the components using connect that are inside the iframe? The library I'm using to create the iframe is the following: https://github.com/ryanseddon/react-frame-component

Any help is appreciated.

**Comment by timjacobi** [comment]
`react-redux` makes the store available in your react application via *context*. See https://facebook.github.io/react/docs/context.html for more information on context.

The root of every react application is the component passed to `ReactDOM.render`. When you have a look at the source code of `react-frame-component` you will see that the iframe content is created by calling `ReactDOM.render` again and handing the result to the iframe ([see here](https://github.com/ryanseddon/react-frame-component/blob/master/index.js#L55)).

As you can [see here](https://github.com/ryanseddon/react-frame-component/blob/master/index.js#L41) the context is not passed to the React application that lives in the iframe so this is actually a problem with `react-frame-component` and not `react-redux`.

You should be able to circumvent the problem by wrapping your iframe content like this
```JavaScript
<Provider store={store}>
// content
</Provider>
```

**Comment by lucadegasperi** [comment]
Okay Thanks, next questions: How do i access the store from inside a component in order to pass it to the provider inside the iframe? And, will these two stores be in sync with each other?

**Comment by timjacobi** [comment]
The store should be available in every component wrapped in the provider via `this.context.store`. Though I had a play with the frame component last night and it worked fine for me. Maybe try and update?

**Comment by lucadegasperi** [comment]
Awesome! Will try right away!

**Comment by timjacobi** [comment]
No problem and I forgot to say: There is only one store being passed around so there won't be any syncing issues.

**Comment by lucadegasperi** [comment]
Thanks Tim! Right now doing ```console.log(this.context);``` in the render method is returning undefined. Any clue on why the context isn't there? The component is defined with React.createClass instead of the new ES6 class syntax.

**Comment by merk** [comment]
this.context is only populated when you define the properties you want in contextTypes

https://facebook.github.io/react/docs/context.html

**Comment by lucadegasperi** [comment]
Just read that after having the issue, context is still a new thing to me :smile:

**Comment by gaearon** [comment]
You can do something like

```js
class MyStuff extends Component { 
  render() {
    return (
      <Frame>
       <Provider store={this.context.store}>
         <WhateverIsInside />
       </Provider>
      </Frame>
    );
  }
}
MyStuff.contextTypes = {
  store: React.PropTypes.object.isRequired
};
```

(pseudocode)

**Comment by gaearon** [comment]
The reason this problem exists is because React doesn't preserve context across `ReactDOM.render()` boundaries which is what that frame component uses.

**Comment by timjacobi** [comment]
@lucadegasperi I have raised an issue against the frame component and it's being worked on.
https://github.com/ryanseddon/react-frame-component/issues/29

**Comment by lucadegasperi** [comment]
@timjacobi for now I have avoided using this technique, good thing someone is working on improving it.

**Comment by ryanseddon** [comment]
Just a heads up I've merged and published a fix for this, all kudos goes to @ibash for coming up with the fix.
