### ISSUE TITLE
change dispatch property getting removed

### ISSUE THREAD

**Issue by arolson101** [rackt/react-redux#241]
I have a reduxForm with a mapDispatchToProps that adds a method "change" (mapped to reduxForm.change), but it doesn't end up on this.props.  If I rename it to "props2" then it does.

```js
@reduxForm.reduxForm(
  ...
  (dispatch) => bindActionCreators({
    change: reduxForm.change
  }, dispatch)
)
```

this was working when I was using ```@connect``` with the mapDispatchToProps

**Comment by gaearon** [comment]
The right place to file this in Redux Form repo.
You're having issues with their code after all, not ours :wink:

**Comment by arolson101** [comment]
d'oh!  sorry.
