### ISSUE TITLE
Supports props list in @connect()

### ISSUE THREAD

**Issue by julien-f** [rackt/react-redux#244]
For the `mapStateToProps` parameters, it would be nice to be able to pass a list of properties to map:

```js
@connect([ 'prop1', 'prop2', 'prop3' ])
class MyComponent { ... }
```

Instead of having to write:

```js
@connect(s => {
  s.prop1: prop1,
  s.prop2: prop2,
  s.prop3: prop3
})
class MyComponent { ... }
```

**Comment by epeli** [comment]
Curried pick function is cool for this:

```js
@connect(R.pick([ 'prop1', 'prop2', 'prop3' ]))
class MyComponent { ... }
```
R is Ramda in this example

**Comment by gaearon** [comment]
We don't want to add syntax sugar like this. It dilutes the library API, optimizing for a somewhat common case, but making it much less obvious that you can do any kind of custom processing inside that function.
