### ISSUE TITLE
Synthetic Mouse Event dispatched non-explicitly

### ISSUE THREAD

**Issue by cdaringe** [rackt/react-redux#246]
Hi all:

I don't understand what's going on, and would love some tips!  I've bound a mouse click event to a function, which does _nothing_--it's a no-op.  Yet, when I click the button to trigger the handler, somewhere down the stack `ReactErrorUtils` does calls `dispatchEvent` (see below ref), which taps into redux, via dispatching the mouse event.  Redux then complains "Cannot read property 'type' of undefined", which is reasonable, because _I never personally dispatched the mouse event_.

To be more specific, I have a connected component, `UserController` and a dumb component to go with it.  The `logout` method (a no-op), is passed through, and _is not meddled with at all_ anywhere inbetween.  On click of the button, logout is entered into as expected, then post-return of said handler, the erroring call stack occurs.

About to get on a flight, but will follow up soon.  Let me know what else I can provide!

```
TypeError: Cannot read property 'type' of undefined
    at /Users/cdieringer/node/coinstac/node_modules/redux-logger/lib/index.js:129:48
    at /Users/cdieringer/node/coinstac/node_modules/redux-promise/lib/index.js:21:60
    at /Users/cdieringer/node/coinstac/node_modules/redux-thunk/lib/index.js:9:74
    at /Users/cdieringer/node/coinstac/node_modules/redux/lib/utils/bindActionCreators.js:14:12
    at Object.ReactErrorUtils.invokeGuardedCallback (webpack:///../~/react/lib/ReactErrorUtils.js?:71:16)
    at executeDispatch (webpack:///../~/react/lib/EventPluginUtils.js?:79:21)
```

```js
// ReactErrorUtils.js
...
if (process.env.NODE_ENV !== 'production') {
  /**
   * To help development we can get better devtools integration by simulating a
   * real browser event.
   */
  if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function' && typeof document !== 'undefined' && typeof document.createEvent === 'function') {
    var fakeNode = document.createElement('react');
    ReactErrorUtils.invokeGuardedCallback = function (name, func, a, b) {
      var boundFunc = func.bind(null, a, b);
      var evtType = 'react-' + name;
      fakeNode.addEventListener(evtType, boundFunc, false);
      var evt = document.createEvent('Event');
      evt.initEvent(evtType, false, false);
      fakeNode.dispatchEvent(evt); // <== line 71, from the above stack
      fakeNode.removeEventListener(evtType, boundFunc, false);
    };
  }
```

**Comment by cdaringe** [comment]
my app is here: https://github.com/MRN-Code/coinstac/tree/feature/tidy-process-service-roles/app/render
the component is here: https://github.com/MRN-Code/coinstac/blob/feature/tidy-process-service-roles/app/render/components/user-account-controller.js#L17

unfortunately the backend server for supporting the services isn't readily accessible, hence you'd have to hack it a bit to even get logged in (in order to logout to observe the issue!).

**Comment by cdaringe** [comment]
In a nutshell, I don't expect the MouseEvent to be dispatched like a redux action, but its getting tangled into the redux action flow!  Bummer!

**Comment by cdaringe** [comment]
NM.  I see the issue.  How embarrasing :)

**Comment by gaearon** [comment]
What was the issue?

**Comment by cdaringe** [comment]
The action creator was bound (to dispatch) already.  Everything was behaving as expressed in the file.  I simply didn't expect the above because of different implementation strategies between a coworker and myself.

I prefer `dispatch(actionCreator())`.  He preferred `bindActionCreators(...)` then `actionCreator()`.  Inconsistent conventions used between us was the root of the issue--I didn't see that it had already been bound.

**Comment by gaearon** [comment]
Ah, fair enough!
