### ISSUE TITLE
@connect as HOC?

### ISSUE THREAD

**Issue by JoeGrasso** [rackt/react-redux#252]
I am trying to avoid contextTypes as well as redundant code. I have different types of products, ie current products, discontinued products, seasonal products, etc. As I understand containers, I cannot put them all in one container as they are in different sections (pages) of the website. What I would like to do is extrapolate out the data fetching from the container and have it as a higher order component that the one below and others can call upon for the data w/o resorting to redundant code. 

Any ideas? Now respectfully, you brainiacs have a tendency to be terse and unintentionally nebulous in your explanation, so please assume I am as dumb as a bunch of rocks.

Thanks.

Below is my current container:

    @connect(state => ({
       products: state.productsReducer.products
    }))
    export default class AppContainer extends Component {
      constructor(props) {
        super(props);
      }

      componentDidMount() {
        const { dispatch } = this.props;
        const clientId = this.context.clientInfo._id;
        dispatch(fetchProductsIfNeeded(clientId));
      }

     // get from parent
     static  contextTypes = {
        clientInfo: PropTypes.object.isRequired
      };

      static propTypes = {
        children: PropTypes.node.isRequired,
        dispatch: PropTypes.func.isRequired,
        products: PropTypes.array
     };
 
          .....
      // This is where my contextTypes would be for child components to receive products
     // but I would like to avoid that and instead create a HOC that this and other components
     // can retrieve the data.
 
      render() {
        if (!this.props.products) return <Plugins.Loading />;
        .....
        return (
          <section style={ radStyles.body }>
            <Layout.Header user={ user } handleLogout={ () => this.handleLogout() }/>
            { this.props.children }
            <Layout.Footer />
          </section>
          );
        }
     };

**Comment by tkh44** [comment]
You could just make a component called ProductWrapper or something like that and connect it to the redux store.  Its purpose would be gather your product data and or filter based on props and it would just render its children with the added products prop. See [cloneElement](https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement)

    ...
    render() {
      .....
      return (
        <ProductWrapper discontinued={false} season='christmas' saleItemsOnly={true}>
          <ProductPageFeatureShowingTopItem/> // This would have products as a prop
          <ProductPageListDisplay/> // So would this
        </ProductWrapper>
      );
      ...


This is a contrived example, but it would be a simple solution and your fetching and filtering for that data could be in one component and used for all your product pages.

**Comment by JoeGrasso** [comment]
That did absolutely nothing to clear this up for me.

**Comment by gaearon** [comment]
Don't forget `connect()` is just a function.
You don't have to use the decorator syntax :-).

Normally I'd create a single `<Products>` presentational component.
Then I'd use `connect()` in different files to create different containers for it:

```js
// AwesomeProducts
const AwesomeProducts = connect(
  state => state.awesomeProducts,
  AwesomeProductActions
);

// AmazingProducts
const AmazingProducts = connect(
  state => state.amazingProducts,
  AmazingProductActions
);
```

This is oversimplified but you should get the idea. You can have many containers all wrapping the same presentational component, but supplying different ways of selecting the data. Similarly you can create your own `connectProducts()` that calls `connect()` but abstracts away data fetching and similarities in state selection logic.
