### ISSUE TITLE
Completely lost on containers concept .....

### ISSUE THREAD

**Issue by JoeGrasso** [rackt/react-redux#254]
I am completely lost on the react-redux container (ie connector) concept as it is not doing what I anticipated. My issue is straight forward, and to me reasonable, yet I cannot find a well written example of how to accomplish it.

Let us say we have a react component that connects to a store that has product context, and we will call this component `ProductContext`. 

Furthermore, let's say we want to reuse `ProductContext` liberally throughout the app so as to avoid the boilerplate code of dispatching actions on every other component that may need products. 

Illustratively this is what I mean:

  **from DiscountuedProducts:**

    <ProductContext >
       // do something with props from container
    </ProductContext >

  **from SeasonalProducts:**

    <ProductContext >
       // do something with props from container
    </ProductContext >

From the examples I see at react-redux, it appears to me that their containers lump both seasonal and discontinued products in the container itself. How is that reusable? 

**from the ProductContextComponent:**

    <section >
      <DiscontinuedProducts />
      <SeasonalProducts />
    </section >

Complicating matters, while trying to keep a cool head about this most frustrating matter, "nebulous tersity" seems to be the only responses I receive.

So here is my `ProductContext`:

    @connect(state => ({
       products: state.productsReducer.products
    }))
    export default class ProductContext extends Component {
      constructor(props) {
        super(props);
      }
    
      componentDidMount() {
        const { dispatch } = this.props;
        const clientId = this.context.clientInfo._id;
        dispatch(fetchProductsIfNeeded(clientId));
      }
    
     // get from parent
     static  contextTypes = {
        clientInfo: PropTypes.object.isRequired
      };
    
      static propTypes = {
        children: PropTypes.node.isRequired,
        dispatch: PropTypes.func.isRequired,
        products: PropTypes.array
     };
    
   
      render() {
        if (!this.props.products) return <Plugins.Loading />;
        .....
        return (
             // I want to put the products array here
          );
        }
     };

Then my thinking is if I do this:

  **from DiscountuedProducts:**

    <ProductContext >
       // do something with props from container
    </ProductContext >

`DiscontinuedProducts` should have knowledge of those products and it can simply filter for what is discontinued.

Am I completely wrong on this? Is this not reasonable to desire?

If anyone knows of a **exhaustive** example on the Net demonstrating how this can be achieved, I would much appreciate it being pointed out to me. I have spent over a week on this issue and am about ready to give up on react-redux.

**Comment by gaearon** [comment]
Unfortunately I really don't understand what you're trying to do. Can you describe the same problem but remove all mentions of context (please don't use context! It's mostly meant for library authors, not for apps) and describe it from the point of view of **the problem you're solving, not the implementation you tried.** That is, describe the components you want to see on the screen, and how you want to compose them, but don't describe the implementation you tried.

**Comment by gaearon** [comment]
Also please ask this on StackOverflow. (Feel free to post the link here.) This is not the right place for very localized questions.
