### ISSUE TITLE
Context store name

### ISSUE THREAD

**Issue by nickdima** [rackt/react-redux#268]
I see that the store is set on on the context with the name `store` which is fine in most cases but since the context is global there are case when you need it to be more specific.
I have an existent app which I want to port to Redux incrementally but it already has something called `store` on the context.
The solutions I see here are either choose a more specific name eg. `reduxStore` or have it passed as a prop to `Provider`.
I could make a pull request if any of these two are acceptable.

**Comment by danmartinez101** [comment]
Taking an example from another Rackt project: https://github.com/rackt/react-router/blob/449fefa4d55025ea459d6b9e2e3aa7169e00b0f5/examples/master-detail/app.js#L66

react-router => context.router
react-redux => context.redux

**Comment by nickdima** [comment]
So, what are you suggesting?

**Comment by danmartinez101** [comment]
I'm suggesting the context property for react-redux be "redux" in the same way that react-router's is "router".

**Comment by nickdima** [comment]
Yeah, that's definitely the way to go. Should we CC someone that has merge privileges before making a pull request?

**Comment by danmartinez101** [comment]
I'd say just go ahead and make a PR for it and reference this issue in the descriptions. When they have time, they will review and comment / decide; no need to cc imo.

**Comment by gnoff** [comment]
> I'm suggesting the context property for react-redux be "redux" in the same way that react-router's is "router".

I thought the same thing at first but react-router is still claiming a implementation non-specific namespace on context. they technically have the same problem we have with `store`. i've commented on the PR regarding supporting as `as` prop which optionally places the store in another namespace on context. I don't think this change is worth breaking everyone who has depended on the store outside of Provider and connect personally

**Comment by gaearon** [comment]
Please see my response in https://github.com/rackt/react-redux/pull/272#issuecomment-175215719.
