### ISSUE TITLE
New parent props don't re-render the component

### ISSUE THREAD

**Issue by alantrrs** [rackt/react-redux#282]
Using ``react-redux: 4.3.0`` I'm passing props to my connect()'ed component ``MyComponent`` from its parent component. However they're not re-rendering ``MyComponent``. I only need ``connect()`` for  ``dispatch`` so I'm wrapping my component like this:
```js
exports default connect()(MyComponent)
```

Removing ``connect()`` fixes the issues.
is this expected behavior?

**Comment by gaearon** [comment]
If your props are mutated deeply, this is expected. React Redux assumes that if `props.foo.a` changes, `props.foo` also changes its reference. This is the only performant way to know when the props change.

If you are affected by this,

* Either change your parent component to make sure the props are not mutated deeply,
* or add `{ pure: false }` as the fourth argument to `connect()` (note: it will be much slower than normally).
