### ISSUE TITLE
[feature-req] Actions on mount parameter

### ISSUE THREAD

**Issue by dzannotti** [rackt/react-redux#47]
Would be nice to have a fourth optional parameter in connect with signature `(props, boundActions) =>` that gets executed once the connected component mounts. It's a very common pattern to want to fetch data from an endpoint on component mounting and would be nice to push side effects into connector rather than the component itself.

**Comment by gaearon** [comment]
@prepare(props => action) where action may be async action?

**Comment by gaearon** [comment]
I'm not sure you'd really need boundActions there. If you give it an action creator, the HOC can take care of dispatching itself.

**Comment by dzannotti** [comment]
Uhm.... I think you need bound actions there because you might want to call multiple (async or not) actions. example
```
(props, boundActions) => { 
  boundActions.getUserProfile(props.userId);
  boundActions.resetFormX()
}```
I'm not 100% sure if this would add confusion/fuel bad practices among newcomers, but i think that most people would have to use lifecycle events to achieve this, so why not facilitate it into the connector itself, other flux framework offer routeActions (which are pretty much this) and it's a common enough topic of questioning on slack

**Comment by dzannotti** [comment]
This also could possibly facilitate the promise collection needed for server side initial rendering

**Comment by gaearon** [comment]
I'd like to see this as a separate package in userland first. When its API is nailed, we can consider including it.

**Comment by volkanunsal** [comment]
@dzannotti Is it possible to call an action from within another action right now? If it were possible, this might be better done from an action. 

This also reminds me of Cerebral's signals, which stack of actions.

**Comment by gaearon** [comment]
Yes, you can do this with redux-thunk or similar middleware.

```js
// assuming redux-thunk
function prepareComponent(props) {
  return function (dispatch) {
    dispatch(getUserProfile(props.userId));
    dispatch(resetFormX());
  }
}

@prepare(prepareComponent) 
...
```

The only problem is we want to only do this when specific prop changes.

**Comment by dzannotti** [comment]
Interesting, I didn't think about that, recalling it on props change should be trivial, knowing if it's needed or not might not be

**Comment by gaearon** [comment]
That's why I'm not sure there's a general nice solution here. Different projects may solve this differently.

**Comment by gaearon** [comment]
Interesting pattern: passing custom function instead of action creator as second parameter:

```js
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { fetchUser, fetchRepos } from '../actions';
import User from '../components/User';

class UserPage extends Component {
  componentWillMount() {
    this.props.fetchData(this.props.userLogin);
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.userLogin !== this.props.userLogin) {
      this.props.fetchData(nextProps.userLogin);
    }
  }

  render() {
    const { user } = this.props;
    if (!user) {
      return <h1>Loading...</h1>;
    }

    return (
      <div>
        <User {...user} />
      </div>
    );
  }
}

UserPage.propTypes = {
  user: PropTypes.object,
  userLogin: PropTypes.string.isRequired,
  fetchData: PropTypes.func.isRequired
};

function mapStateToProps(state) {
  return {
    users: state.database.users
  };
}

function mergeProps(stateProps, dispatchProps, ownProps) {
  const { users } = stateProps;
  const { userLogin } = ownProps.params;

  return Object.assign({}, dispatchProps, {
    user: users[userLogin],
    userLogin
  });
}

function fetchData(userLogin) {
  return dispatch => Promise.all([
    dispatch(fetchUser(userLogin)),
    dispatch(fetchRepos(userLogin))
  ]);
}

export default connect(
  mapStateToProps,
  { fetchData },
  mergeProps
)(UserPage);
```

**Comment by dzannotti** [comment]
That's pretty much the pattern i was looking for, but i need bind action + `fetchData`

**Comment by gaearon** [comment]
Why do you need it to be bound there?

```js
function fetchData(userLogin) {
  return dispatch => {
    return Promise.all([
      dispatch(fetchUser(userLogin)),
      dispatch(fetchRepos(userLogin))
    ]).then(() => dispatch(resetForm());
  };
}
```

**Comment by dzannotti** [comment]
Oh no, i don't, i just need boundActions to be passed down to the component, that's all

**Comment by dzannotti** [comment]
Yeah re-reading the pattern is slightly off from what i normally use/need.

```
connect((state) => mereStateToProps, actionCreators, (props, dispatch) => {
// execute this on mount/props change
dispatch(fetchData());
})(MyComponent);
```
this would allow MyComponent to remain pure while still having route based actions

**Comment by malte-wessel** [comment]
Take a look at this (decorator) function. https://github.com/broucz/threads-redux/blob/master/client/decorators/onUpdate.js

The callback is only invoked if certain parameters change.

**Comment by gaearon** [comment]
While I'm happy to see this in userland, I don't think it belongs in `react-redux`.

**Comment by gaearon** [comment]
Here's [another example](https://github.com/emmenko/redux-react-router-async-example/blob/ef5e3f51b6d27f153bdb8492aab670f30cf70067/lib/decorators/fetchOnUpdate.js) of such HOC from [redux-react-router-async-example](https://github.com/emmenko/redux-react-router-async-example):

```js
import React, { PropTypes } from 'react'
import shallowEqual from 'react-redux/lib/utils/shallowEqual'

function mapParams (paramKeys, params) {
  return paramKeys.reduce((acc, key) => {
    return Object.assign({}, acc, { [key]: params[key] })
  }, {})
}

export default function fetchOnUpdate (paramKeys, fn) {

  return DecoratedComponent =>
  class FetchOnUpdateDecorator extends React.Component {

    static propTypes = {
      actions: PropTypes.object
    }

    componentWillMount () {
      fn(mapParams(paramKeys, this.props.params), this.props.actions)
    }

    componentDidUpdate (prevProps) {
      const params = mapParams(paramKeys, this.props.params)
      const prevParams = mapParams(paramKeys, prevProps.params)

      if (!shallowEqual(params, prevParams))
        fn(params, this.props.actions)
    }

    render () {
      return (
        <DecoratedComponent {...this.props} />
      )
    }
  }
}
```

[Usage example](https://github.com/emmenko/redux-react-router-async-example/blob/ef5e3f51b6d27f153bdb8492aab670f30cf70067/lib/components/github/Repo.js#L7-L11):

```js
@fetchOnUpdate([ 'username', 'repo' ], (params, actions) => {
  const { username, repo } = params
  actions.fetchRepo({ username, repo })
  actions.fetchRepoStargazers({ username, repo })
})
export default class Repo extends React.Component {
  ...
}
```
