### ISSUE TITLE
Maintain static functions

### ISSUE THREAD

**Issue by erikras** [rackt/react-redux#53]
Could `connect()` check its wrapped component for static functions and add them to the returned component? For things like `fetchData()` and `onEnter()`. Seems like it would be pretty easy to go through the keys and check if `typeof WrappedComponent[key] === 'function'`.

Just a thought.

**Comment by gaearon** [comment]
I wouldn't do that. It's only going to make things worse IMO: https://github.com/acdlite/flummox/issues/173#issuecomment-100552563

**Comment by erikras** [comment]
Good call. I briefly looked into implementing it and the code disgusted me.

**Comment by gaearon** [comment]
I'm happy to reconsider it using https://github.com/mridgway/hoist-non-react-statics since we don't have to maintain it. Wanna make a PR?

**Comment by erikras** [comment]
I was going to complain about the lack of docs for that library, but then I saw how utterly trivial the code is. Also, I can't remember the time I last used the word "hoist"; such a good word.

Will add the PR to the todo list.

**Comment by erikras** [comment]
I just, by chance, ran into a problem in my app where I need this functionality. Any chance of a release soon?

**Comment by gaearon** [comment]
Give me a few days, vacation :-)

**Comment by epeli** [comment]
If in hurry you can do it in userland:

```js
MyComponentConnected = hoistNonReactStatics(connect(mapState)(MyComponent), MyComponent);
```

It should be future compatible.

**Comment by erikras** [comment]
You and your pink crocs enjoy your vacation. No hurry. :shell: :ocean: :sunny: 

For now I've just done `MyComponent.WrappedComponent.onEnter` to get to my `onEnter` function.

**Comment by gaearon** [comment]
Out in 3.1.0.

**Comment by gaearon** [comment]
Lol. I knew this is going to come back and bite me in the arse.
https://github.com/reactjs/react-redux/issues/163#issuecomment-192556637
