### ISSUE TITLE
[just ideas] - Option for dealing with deep component prop passing within Connected components

### ISSUE THREAD

**Issue by gnoff** [rackt/react-redux#61]
Apologies for polluting the issue list since it's not really an issue but I believe there is some interest in coming up with a workable solution that

a) Keeps the Smart/Dumb component divide clean & generally near the top of the component tree for a given part of the app domain AND
b) Avoid the hassle of passing @connect results down deep chains of children

I liked the Provide/connect pattern a lot so I generalized it in [react-tunnel](https://github.com/gnoff/react-tunnel) and starting playing with a patter like so

```js
// in some Top level Component
<Provider store={mystore} /> //react-redux Provider
  {() => <App />}
</Provider>

// in a route handler
@connect(
  myStateMapper,
  (dispatch) => ({
    someActions: bindActionCreators(subsetOfMyActions, dispatch)
  })
)
export class ConnectedComponent...

// within ConnectedComponent's render()
<Provider someActions={this.props.someActions}> //react-tunnel Provider
  {() => <PageController />}
</Provider>

// deep within PageController's render tree
@inject(
  (provided) => ({
    specificActionIwant: someActions.specificActionIwant
  })
)
export class DeepComponent...

//within DeepComponent's lifecycle methods
...
this.props.specificActionIWant();
...
```

The Provider in react-tunnel puts props into context under the provided namespace and inject pulls them off with the mapProvidedToProps function.

It's not react-redux specific nor really related to redux in any way (and there are probably plenty of other DI type libraries that will get the same job done) but i thought it fit nicely with the react-redux paradigm but would give you the option to use similar semantics deeper in the component tree without bringing along anything specific to redux.

As a final note, you could actually do away wiht the react-redux Provider and just use the react-tunnel provider and inject by doing

```js
// near top of app
<Provider store={mystore}>  //react-tunnel Provider
  {() => <App />}
</Provider>

//when you are going to connect...
@connect(
  stateFn,
  actionFn
)
@inject( provided => ({store: provided.store}) )
export class InjectedThenConnectedComponent...

//the above would have store made available to connect via props and not context but that is now supported in react-redux
```

anyhow, just some food for thought... would love feedback even if it's why this is a horrible idea.

Thanks,
Josh

**Comment by gnoff** [comment]
Closing, no real traction here.

**Comment by gaearon** [comment]
It'll be easier to experiment with this stuff when 0.14 ships, but yeah, not really related to Redux.

I'm not convinced a middle solution is needed here. Having several context split points makes it harder to move components around the app, as dependencies become implicit.

**Comment by gnoff** [comment]
Agreed on the context splits concern but I do think that by pushing the connect to route handler style tier of a component tree ( which is nice for exactly the reasons you suggest it re: redux aware/unaware splits) we leave on the table the perennial problem of contexualizing the output of connect for use by the whole child tree. In shallow trees this isn't much of a concern but for complex and deep ones it is.

I can imagine that some will start to connect their leaf components using the mapDispatchToProps argument only which gets the job done, but only for that use case (providing action creators deeply) and ties their implementation to the react redux dependency unnecessarily.

One doesn't really need tunnel in that you can manage this all via the context feature (presumably it will be documented in 0.14) but then that is also the case for react-redux's provider too now that store can be loaded from props in connect.

Are you in particular an advocate for vanilla prop passing everything? Or vanilla context use?

To be clear I suspect that react-tunnel can and will be abused overused and cause problems of its own. Not sure what to do about that other than discouraging bad practices.

**Comment by gaearon** [comment]
>Are you in particular an advocate for vanilla prop passing everything? Or vanilla context use?

I try to `connect()` route handlers and use props all the way down unless some component gets too complicated and then it gets its own `connect()`, but also gets a “dumb” props-only version in case I want to reuse it later.

**Comment by gnoff** [comment]
Makes sense, I guess i would just replace the deep `connect()` with `inject()` since it isn't strictly bound to the semantics of redux. The thing about either option is that they map what is contextual information into props so that you the 'dumb' version doesn't care how it get's its props and this means you can easily partially or fully unwind this style of props providing without having to refactor said component.
