### ISSUE TITLE
Specifying root component as a function in React 0.14

### ISSUE THREAD

**Issue by billyjanitsch** [rackt/react-redux#64]
The [readme](https://github.com/rackt/react-redux#injecting-redux-store) mentions that the child of `Provider` will no longer have to be specified as a function starting in React 0.14. I'm using 0.14 (beta 3) in a current project, but `react-redux` yells at me if I don't provide the child as a function.

Any chance of disabling this warning now that 0.14 is in beta? (Perhaps in a beta npm release, if you'd prefer?)

Thanks for your work on Redux!

**Comment by gnoff** [comment]
We would need to do more than disable the warning, the Provider render method would need to be updated to conditionally call children in react 13 and simply render children in react 14. I'm not actually sure how to detect the react version at runtime, I suppose it is possible but it's more likely that we will just wait to release a version bump when 14 comes out that has a strict peer dependency on react 14 along with the api improvement. 

Can't speak for Dan though so who knows.

**Comment by gaearon** [comment]
I'm happy to accept a PR doing this, but I'm also not sure about “checking React version” bit (and whether we even want to attempt doing this).

I'd rather release a version depending hard on 0.14+ once it comes out, that has the right behavior. Feel free to submit a PR to implement this behavior so we can merge it once React 0.14 is out.

**Comment by gaearon** [comment]
Let's track this in https://github.com/rackt/react-redux/pull/70.
