### ISSUE TITLE
Problems with context

### ISSUE THREAD

**Issue by gyzerok** [rackt/react-redux#79]
I'm trying to build my own components on top of react-redux. I'm stuck with the following error:
```
Uncaught Error: Invariant Violation: Could not find "store" in either the context or props of "Connect(SmartComponent(App))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(SmartComponent(App))".
```

My components need to have their own childContext. Mb I need somehow to merge childContext of my components with one from react-redux?

**Comment by gnoff** [comment]
Are you using a `<Provider>` higher up in your component tree than the component that you are using `connect` on?

**Comment by gaearon** [comment]
There is nothing we can help you with unless you provide a full example.
Please reopen when there is something we can run and test.

>Mb I need somehow to merge childContext of my components with one from react-redux?

No, React merges context.

**Comment by gyzerok** [comment]
@gaearon sorry for not closing an issue, I've already find the solution.

**Comment by gaearon** [comment]
What was it?

**Comment by gyzerok** [comment]
```javascript
const router = (
  <Router history={history}>
    // routes here
  </Router>
);

<Provider>
  {() => router}
</Provider>
```
Was not obvious for me that Router component itself have to be declared in the function body.

**Comment by gaearon** [comment]
Got it!
It's documented: https://github.com/rackt/react-redux#could-not-find-store-in-either-the-context-or-props

**Comment by gyzerok** [comment]
@gaearon I guess here is another problem. I thougt that if I place router as and return from function inside Provider it would be similar to put <Router> tag inside Provider. I think its all about how JSX work. Dont know how to describe it better. Hope you can :)

**Comment by gaearon** [comment]
Okay. I think we'll just wait for React 0.14 because the problem will go away with it.
