### ISSUE TITLE
Render not called when dispatch

### ISSUE THREAD

**Issue by K4stor** [rackt/react-redux#87]
Hello

I am trying to port my project to Redux.
My components are react already. And I added 
everything needed (or at least I think so) to 
obey the redux framework. 

But my React Component wont re-render even if I use 
```export default connect(state => state)(WorkspaceView)```

The reducer gets called, the state is altred, but nothing happens.
When I force a render manually it works.

I uploaded my project here  https://dl.dropboxusercontent.com/u/11300320/PTG.zip , and the component I am writing about is called Workspace view.
Just dload it, run ```npm install``` ``` gulp``` and ```./run```.
It uses electron.io therefore the run command
Please help me !

Regards Carsten

**Comment by alanrubin** [comment]
Hi @K4stor I have looked into your code, it seems you are mutating your state in your reducer, you are pushing a new entry into operations array instead of creating a new array. See http://rackt.github.io/redux/docs/basics/Reducers.html or http://rackt.github.io/redux/docs/Troubleshooting.html in the first section. Your state needs to be immutable so that re-render is triggered. Hope it helps !

**Comment by K4stor** [comment]
Ah ok that makes sense. Thank you very much !

**Comment by gaearon** [comment]
https://github.com/rackt/react-redux#my-views-arent-updating

**Comment by bdavisx** [comment]
Just wanted to update the link that Dan posted above, the troubleshooting section has moved and this shows up pretty high in searches: 

https://github.com/reactjs/react-redux/blob/master/docs/troubleshooting.md#my-views-arent-updating

**Comment by markerikson** [comment]
Yeah, mutating state is the reason for components not updating like 98% of the time.  I've written up an answer on this in my FAQ.  It's not merged in yet, so I'll link to the WIP branch: https://github.com/markerikson/redux/blob/merge-faq-page/docs/FAQ.md#why-isnt-my-component-re-rendering-or-my-mapstatetoprops-running

**Comment by vincent714** [comment]
just as @alanrubin said, it needs a new array
