### ISSUE TITLE
can i wrap multi actionCreators into one props with name?

### ISSUE THREAD

**Issue by geminiyellow** [rackt/react-redux#89]
We can 

`Inject todoActionCreators as todoActions, and counterActionCreators as counterActions`

`Inject todoActionCreators and counterActionCreators together as actions`

now. 

can i Inject todoActionCreators as todoActions, and counterActionCreators as counterActions, and then together as actions?

```
{
  actions: {
    todoActions,
    counterActions,
  }
} 
```

**Comment by gaearon** [comment]
Yes. It's not magic: you can do anything you want.

```js
import * as todoActions from './todoActions';
import * as counterActions from './counterActions';
import { bindActionCreators } from 'redux';

function mapStateToProps(state) {
  return { todos: state.todos };
}

function mapDispatchToProps(dispatch) {
  return {
    actions: {
      todoActions: bindActionCreators(todoActionCreators, dispatch),
      counterActions: bindActionCreators(counterActionCreators, dispatch)
    }
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(TodoApp);
```

**Comment by honpery** [comment]
hi, I have also the same problem, I use *4.4.5* version react-redux, it isn't work. The feature has removed?

**Comment by honpery** [comment]
Thank you very much, good work!!!

**Comment by amorenew** [comment]
https://github.com/reactjs/redux/issues/363
bindActionCreators({ ...SomeActions, ...OtherActions }, dispatch)

**Comment by todorpr** [comment]
I came to this page while looking for a way to combine multiple action creators

Trying to simplify @gaearon example I ended with this one:
```
const mapDispatchToProps = (dispatch) => {
  return {
    actions: bindActionCreators({ ...todoActions, ...counterActions}, dispatch)
  }
};
```

though probably it's better for the different action creators to be separated in different categories such as - `todoActions` and `counterActions`, still I'm posting this example for reference.

**Comment by a-m-dev** [comment]
can we have it like all in one place ??? something like:


```
function mapDispatchToProps(dispatch) {
  return {
    actions: {
      actions: bindActionCreators({ todoActions, counterActions }, dispatch),
    }
  };
}
```


can we ?????
