### ISSUE TITLE
Using latest version of react-redux together with redux-devtools breaks

### ISSUE THREAD

**Issue by davidpelayo** [rackt/react-redux#91]
**NOTE** [Also on redux-devtools repo](https://github.com/gaearon/redux-devtools/issues/96)

I have executed ```ncu -u``` to upgrade my package dependencies, to have the settlement like described below:

Previous versions:
```json
{
  "react-redux": "^0.2.2",
  "redux-devtools": "^0.1.2"
}
```

New versions:
```json
{
  "react-redux": "^2.1.0",
  "redux-devtools": "^2.1.0"
}
```

 And after installing newer package versions, saw an error displayed on console:

```javascript
createConnect.js?70ef:76 Uncaught TypeError: store.getState is not a function
```

After searching for a while, I realised, by debugging the injected code by webpack, it had to do with the ```devtools```.

Here the following code snippet:

```javascript
import { devTools, persistState } from 'redux-devtools';
import { DevTools, DebugPanel, LogMonitor } from 'redux-devtools/lib/react';
/*** some other things ***/

const finalCreateStore = compose(
  devTools(),
  persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)),
  createStore
);

/*** some other things ***/

<div className={nameBuilder(componentName, 'content')}>
  <Provider store={store}>
    {() => <Routing {...{history}}/> }
  </Provider>
  <DebugPanel top right bottom>
    <DevTools store={store} monitor={LogMonitor}/>
  </DebugPanel>
</div>
```

If I comment out exactly the imports as well as the ```devTools(), persistState(...),```as well as the ```<DebugPanel>...</DebugPanel>```, simply works.

The reason why isn't working. I don't know. I'm quite new on these technologies and haven't follow issues' discussions you have had around.

I can state then that by using the latest versions of react-redux together with the DebugPanel of redux-devtools, the application crashes not bootstrapping properly.

Hope it helps to figure out.

**Comment by gaearon** [comment]
See here: https://github.com/gaearon/redux-devtools/issues/96#issuecomment-137819220.
