### ISSUE TITLE
Nested connected components trowing Warning: setState(...) 

### ISSUE THREAD

**Issue by Agamennon** [rackt/react-redux#92]
I was on redux v1 and i was having no issues, now i upgraded redux and react-redux and i am getting 
"Warning: setState(...): Can only update a mounted or mounting component."  On some of my components (they are nested connected components), i am trying to find what changed that is causing this with no luck!.

**Comment by gaearon** [comment]
The only way we can help you is if you provide a reproducible example causing the issue.

**Comment by gaearon** [comment]
To clarify: please reopen if you can set up a project that shows the problem.

**Comment by alexkuz** [comment]
This kind of error usually happens when you're trying to update component state in a deferred function (like `setTimeout`), without canceling it in `componentWillUnmount`. I would suggest to check your code for that.

**Comment by Agamennon** [comment]
Made an [example repo](https://github.com/Agamennon/example), details to help understand the example in the repository readme.  @alexkuz  i think that maybe that's whats happening inside react-redux, what is not clear, is how the app is triggering it.

**Comment by gaearon** [comment]
Should be fixed in 2.1.1 via #96.
