### ISSUE TITLE
reopening #92 Nested connected components throwing Warning: setState(...) 

### ISSUE THREAD

**Issue by Agamennon** [rackt/react-redux#95]
Made an [example repo](https://github.com/Agamennon/example), details to help understand the example in the repository readme.

Very grateful if this could be looked into

**Comment by alexkuz** [comment]
@Agamennon It's not working for me :(
First, there is a link to a local repo in `package.json`: 
```
"redux-tiny-router": "file:../redux-tiny-router",
```
I've installed it from npm, but didn't manage to make it work (via `npm start`) - seems like `/build/bundle.js` redirects to index page.

**Comment by Agamennon** [comment]
repo fixed., please try again

**Comment by gaearon** [comment]
FYI, you can reopen existing issues:

<img width="299" alt="screen shot 2015-09-07 at 01 29 15" src="https://cloud.githubusercontent.com/assets/810438/9706930/e36b4ada-54ff-11e5-82e3-5fe0ef425d7d.png">

**Comment by Agamennon** [comment]
@gaearon ,  i don't think i can, the Reopen Issue button does not show up for me.

**Comment by gaearon** [comment]
Oh, I didn't realize this was the case.
Looking into your example now.

**Comment by gaearon** [comment]
There is indeed a bug: if you have unsubscribed during a dispatch, we should ignore the change event.
I'll fix the code shortly.
thanks for reporting.

**Comment by Agamennon** [comment]
@gearon  awsome, thank you!

**Comment by gaearon** [comment]
Should be fixed in 2.1.1 via #96.
