### ISSUE TITLE
React bindings with Relay in mind

### ISSUE THREAD

**Issue by gyzerok** [rackt/react-redux#97]
@gaearon  I've already posted a link to my project about a month ago under the Redux repository. That time it was called `redux-graphql`. I've did a lot of work to understand what it should be. Now I think of it as a React binding for Redux with Relay idea behind.
Today I've ended up with some clunky readme, but I suppose it would be enough for you to get an idea
Now its [adrenaline](https://github.com/gyzerok/adrenaline). Can I somehow contact you to get feedback on what I've done?

**Comment by gaearon** [comment]
Hi, unfortunately I haven't had time to play with GraphQL or Relay yet so I can't comment.
Since there's already a Relay thread in Redux repo, I encourage you to post there instead: https://github.com/rackt/redux/issues/464
