### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by arusakov** [rackt/react-redux#98]
I have seen draft of .d.ts file [there] (https://github.com/rackt/redux/issues/206). But only redux.d.ts file was included to [DefinitelyTyped] (https://github.com/borisyankov/DefinitelyTyped) repo.
react-redux.d.ts will be very helpful!

**Comment by pdeva** [comment]
+1
a .tsd file is really needed

**Comment by gnoff** [comment]
PRs are always welcome. I don't use TS, don't think @gaearon does either. Hopefully someone out there using it will contribute

**Comment by gaearon** [comment]
I'll close because we don't intend to provide or support an official definition.
Please feel free to submit a PR to DefinitelyTyped yourself!

**Comment by thomasboyt** [comment]
@gaearon Any thoughts on reopening this now that Redux has an official definition?

There's a really nasty issue right now where the DefinitelyTyped react-redux definition doesn't actually work correctly with the officially-maintained Redux definition, only the DT Redux definition. It'd be nice if there was an official definition for react-redux that was kept in sync with the official Redux definition :)

**Comment by gaearon** [comment]
Happy to accept a PR adding a definition. I just can't create one myself.
